# Generated by Django 3.0.3 on 2021-02-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('site', models.TextField(max_length=3)),
                ('date_received', models.DateField()),
                ('received_by', models.TextField(max_length=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
