# Generated by Django 3.0.3 on 2021-02-22 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0002_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
