# Generated by Django 4.1 on 2024-04-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tat_sys", "0003_rename_amc_disk_arsrldiskresult_amc_nd20_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amc_disk",
            new_name="amc_nd20",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amc_disk_ris",
            new_name="amc_nd20_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amk_disk",
            new_name="amk_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amk_disk_ris",
            new_name="amk_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amp_disk",
            new_name="amp_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="amp_disk_ris",
            new_name="amp_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="atm_disk",
            new_name="amx_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="atm_disk_ris",
            new_name="amx_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="azm_disk",
            new_name="atm_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="azm_disk_ris",
            new_name="atm_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="caz_disk",
            new_name="azm_nd15",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="caz_disk_ris",
            new_name="azm_nd15_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cec_disk",
            new_name="caz_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cec_disk_ris",
            new_name="caz_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cep_disk",
            new_name="cec_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cep_disk_ris",
            new_name="cec_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cfm_disk",
            new_name="cep_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cfm_disk_ris",
            new_name="cep_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cfp_disk",
            new_name="cfm_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cfp_disk_ris",
            new_name="cfm_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="chl_disk",
            new_name="cfp_nd75",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="chl_disk_ris",
            new_name="cfp_nd75_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cip_disk",
            new_name="chl_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cip_disk_ris",
            new_name="chl_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cli_disk",
            new_name="cip_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cli_disk_ris",
            new_name="cip_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="clr_disk",
            new_name="cli_nd2",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="clr_disk_ris",
            new_name="cli_nd2_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="col_disk",
            new_name="clr_nd15",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="col_disk_ris",
            new_name="clr_nd15_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cro_disk",
            new_name="col_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cro_disk_ris",
            new_name="col_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ctx_disk",
            new_name="cro_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ctx_disk_ris",
            new_name="cro_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cxa_disk",
            new_name="ctx_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="cxa_disk_ris",
            new_name="ctx_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="czo_disk",
            new_name="cxa_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="czo_disk_ris",
            new_name="cxa_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dap_disk",
            new_name="cxm_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dap_disk_ris",
            new_name="cxm_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dor_disk",
            new_name="cza_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dor_disk_ris",
            new_name="cza_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dox_disk",
            new_name="czo_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="dox_disk_ris",
            new_name="czo_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ery_disk",
            new_name="czt_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ery_disk_ris",
            new_name="czt_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="etp_disk",
            new_name="dap_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="etp_disk_ris",
            new_name="dap_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="fep_disk",
            new_name="dor_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="fep_disk_ris",
            new_name="dor_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="fox_disk",
            new_name="dox_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="fox_disk_ris",
            new_name="dox_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="geh_disk",
            new_name="ery_nd15",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="geh_disk_ris",
            new_name="ery_nd15_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="gen_disk",
            new_name="etp_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="gen_disk_ris",
            new_name="etp_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ipm_disk",
            new_name="fdc_nd",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ipm_disk_ris",
            new_name="fdc_nd_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="kan_disk",
            new_name="fep_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="kan_disk_ris",
            new_name="fep_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="lev_disk",
            new_name="fos_nd200",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="lev_disk_ris",
            new_name="fos_nd200_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="lnz_disk",
            new_name="fox_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="lnz_disk_ris",
            new_name="fox_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="man_disk",
            new_name="geh_nd120",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="man_disk_ris",
            new_name="geh_nd120_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mem_disk",
            new_name="gen_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mem_disk_ris",
            new_name="gen_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mfx_disk",
            new_name="imr_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mfx_disk_ris",
            new_name="imr_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mno_disk",
            new_name="ipm_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="mno_disk_ris",
            new_name="ipm_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nal_disk",
            new_name="kan_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nal_disk_ris",
            new_name="kan_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="net_disk",
            new_name="lnz_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="net_disk_ris",
            new_name="lnz_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nit_disk",
            new_name="lvx_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nit_disk_ris",
            new_name="lvx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nor_disk",
            new_name="man_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nor_disk_ris",
            new_name="man_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nov_disk",
            new_name="mem_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="nov_disk_ris",
            new_name="mem_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ofx_disk",
            new_name="mev_nd20",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="ofx_disk_ris",
            new_name="mev_nd20_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="oxa_disk",
            new_name="mfx_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="oxa_disk_ris",
            new_name="mfx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pen_disk",
            new_name="mno_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pen_disk_ris",
            new_name="mno_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pip_disk",
            new_name="nal_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pip_disk_ris",
            new_name="nal_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pol_disk",
            new_name="net_nd30",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="pol_disk_ris",
            new_name="net_nd30_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="qda_disk",
            new_name="nit_nd300",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="qda_disk_ris",
            new_name="nit_nd300_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="rif_disk",
            new_name="nor_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="rif_disk_ris",
            new_name="nor_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sam_disk",
            new_name="nov_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sam_disk_ris",
            new_name="nov_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="spe_disk",
            new_name="ofx_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="spe_disk_ris",
            new_name="ofx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sth_disk",
            new_name="oxa_nd1",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sth_disk_ris",
            new_name="oxa_nd1_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="str_disk",
            new_name="pen_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="str_disk_ris",
            new_name="pen_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sxt_disk",
            new_name="pip_nd100",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="sxt_disk_ris",
            new_name="pip_nd100_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tcc_disk",
            new_name="plz_nd",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tcc_disk_ris",
            new_name="plz_nd_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tet_disk",
            new_name="pol_nd300",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tet_disk_ris",
            new_name="pol_nd300_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tgc_disk",
            new_name="qda_nd15",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tgc_disk_ris",
            new_name="qda_nd15_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tic_disk",
            new_name="rif_nd5",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tic_disk_ris",
            new_name="rif_nd5_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tob_disk",
            new_name="sam_nd10",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tob_disk_ris",
            new_name="sam_nd10_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tzp_disk",
            new_name="spt_nd100",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="tzp_disk_ris",
            new_name="spt_nd100_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="van_disk",
            new_name="sss_nd200",
        ),
        migrations.RenameField(
            model_name="historicalsitediskresult",
            old_name="van_disk_ris",
            new_name="sss_nd200_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="amc_mic", new_name="amc_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="amc_mic_ris",
            new_name="amc_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="amk_mic", new_name="amk_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="amk_mic_ris",
            new_name="amk_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="amp_mic", new_name="amp_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="amp_mic_ris",
            new_name="amp_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="atm_mic", new_name="amx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="atm_mic_ris",
            new_name="amx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="azm_mic", new_name="atm_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="azm_mic_ris",
            new_name="atm_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="caz_mic", new_name="azm_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="caz_mic_ris",
            new_name="azm_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cec_mic", new_name="caz_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cec_mic_ris",
            new_name="caz_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cep_mic", new_name="cec_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cep_mic_ris",
            new_name="cec_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cfm_mic", new_name="cep_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cfm_mic_ris",
            new_name="cep_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cfp_mic", new_name="cfm_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cfp_mic_ris",
            new_name="cfm_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="chl_mic", new_name="cfp_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="chl_mic_ris",
            new_name="cfp_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cip_mic", new_name="chl_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cip_mic_ris",
            new_name="chl_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cli_mic", new_name="cip_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cli_mic_ris",
            new_name="cip_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="clr_mic", new_name="cli_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="clr_mic_ris",
            new_name="cli_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="col_mic", new_name="clr_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="col_mic_ris",
            new_name="clr_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cro_mic", new_name="col_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cro_mic_ris",
            new_name="col_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="ctx_mic", new_name="cro_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="ctx_mic_ris",
            new_name="cro_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="cxa_mic", new_name="ctx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="cxa_mic_ris",
            new_name="ctx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="czo_mic", new_name="cxa_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="czo_mic_ris",
            new_name="cxa_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="dap_mic", new_name="cxm_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="dap_mic_ris",
            new_name="cxm_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="dor_mic", new_name="cza_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="dor_mic_ris",
            new_name="cza_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="dox_mic", new_name="czo_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="dox_mic_ris",
            new_name="czo_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="ery_mic", new_name="czt_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="ery_mic_ris",
            new_name="czt_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="etp_mic", new_name="dap_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="etp_mic_ris",
            new_name="dap_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="fep_mic", new_name="dor_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="fep_mic_ris",
            new_name="dor_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="fox_mic", new_name="dox_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="fox_mic_ris",
            new_name="dox_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="geh_mic", new_name="ery_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="geh_mic_ris",
            new_name="ery_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="gen_mic", new_name="etp_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="gen_mic_ris",
            new_name="etp_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="ipm_mic", new_name="fdc_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="ipm_mic_ris",
            new_name="fdc_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="kan_mic", new_name="fep_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="kan_mic_ris",
            new_name="fep_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="lev_mic", new_name="fos_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="lev_mic_ris",
            new_name="fos_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="lnz_mic", new_name="fox_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="lnz_mic_ris",
            new_name="fox_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="man_mic", new_name="geh_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="man_mic_ris",
            new_name="geh_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="mem_mic", new_name="gen_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="mem_mic_ris",
            new_name="gen_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="mfx_mic", new_name="imr_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="mfx_mic_ris",
            new_name="imr_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="mno_mic", new_name="ipm_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="mno_mic_ris",
            new_name="ipm_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="nal_mic", new_name="kan_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="nal_mic_ris",
            new_name="kan_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="net_mic", new_name="lnz_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="net_mic_ris",
            new_name="lnz_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="nit_mic", new_name="lvx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="nit_mic_ris",
            new_name="lvx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="nor_mic", new_name="man_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="nor_mic_ris",
            new_name="man_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="nov_mic", new_name="mem_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="nov_mic_ris",
            new_name="mem_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="ofx_mic", new_name="mev_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="ofx_mic_ris",
            new_name="mev_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="oxa_mic", new_name="mfx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="oxa_mic_ris",
            new_name="mfx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="pen_mic", new_name="mno_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="pen_mic_ris",
            new_name="mno_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="pip_mic", new_name="nal_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="pip_mic_ris",
            new_name="nal_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="pol_mic", new_name="net_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="pol_mic_ris",
            new_name="net_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="qda_mic", new_name="nit_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="qda_mic_ris",
            new_name="nit_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="rif_mic", new_name="nor_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="rif_mic_ris",
            new_name="nor_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="sam_mic", new_name="nov_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="sam_mic_ris",
            new_name="nov_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="spe_mic", new_name="ofx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="spe_mic_ris",
            new_name="ofx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="sth_mic", new_name="oxa_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="sth_mic_ris",
            new_name="oxa_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="str_mic", new_name="pen_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="str_mic_ris",
            new_name="pen_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="sxt_mic", new_name="pip_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="sxt_mic_ris",
            new_name="pip_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tcc_mic", new_name="plz_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tcc_mic_ris",
            new_name="plz_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tet_mic", new_name="pol_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tet_mic_ris",
            new_name="pol_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tgc_mic", new_name="qda_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tgc_mic_ris",
            new_name="qda_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tic_mic", new_name="rif_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tic_mic_ris",
            new_name="rif_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tob_mic", new_name="sam_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tob_mic_ris",
            new_name="sam_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="tzp_mic", new_name="spt_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="tzp_mic_ris",
            new_name="spt_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="van_mic", new_name="sss_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="van_mic_ris",
            new_name="sss_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="amc_disk", new_name="amc_nd20",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="amc_disk_ris",
            new_name="amc_nd20_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="amk_disk", new_name="amk_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="amk_disk_ris",
            new_name="amk_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="amp_disk", new_name="amp_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="amp_disk_ris",
            new_name="amp_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="atm_disk", new_name="amx_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="atm_disk_ris",
            new_name="amx_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="azm_disk", new_name="atm_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="azm_disk_ris",
            new_name="atm_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="caz_disk", new_name="azm_nd15",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="caz_disk_ris",
            new_name="azm_nd15_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cec_disk", new_name="caz_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cec_disk_ris",
            new_name="caz_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cep_disk", new_name="cec_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cep_disk_ris",
            new_name="cec_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cfm_disk", new_name="cep_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cfm_disk_ris",
            new_name="cep_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cfp_disk", new_name="cfm_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cfp_disk_ris",
            new_name="cfm_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="chl_disk", new_name="cfp_nd75",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="chl_disk_ris",
            new_name="cfp_nd75_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cip_disk", new_name="chl_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cip_disk_ris",
            new_name="chl_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cli_disk", new_name="cip_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cli_disk_ris",
            new_name="cip_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="clr_disk", new_name="cli_nd2",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="clr_disk_ris",
            new_name="cli_nd2_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="col_disk", new_name="clr_nd15",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="col_disk_ris",
            new_name="clr_nd15_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cro_disk", new_name="col_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cro_disk_ris",
            new_name="col_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="ctx_disk", new_name="cro_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="ctx_disk_ris",
            new_name="cro_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="cxa_disk", new_name="ctx_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="cxa_disk_ris",
            new_name="ctx_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="czo_disk", new_name="cxa_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="czo_disk_ris",
            new_name="cxa_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="dap_disk", new_name="cxm_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="dap_disk_ris",
            new_name="cxm_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="dor_disk", new_name="cza_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="dor_disk_ris",
            new_name="cza_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="dox_disk", new_name="czo_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="dox_disk_ris",
            new_name="czo_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="ery_disk", new_name="czt_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="ery_disk_ris",
            new_name="czt_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="etp_disk", new_name="dap_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="etp_disk_ris",
            new_name="dap_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="fep_disk", new_name="dor_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="fep_disk_ris",
            new_name="dor_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="fox_disk", new_name="dox_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="fox_disk_ris",
            new_name="dox_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="geh_disk", new_name="ery_nd15",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="geh_disk_ris",
            new_name="ery_nd15_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="gen_disk", new_name="etp_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="gen_disk_ris",
            new_name="etp_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="ipm_disk", new_name="fdc_nd",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="ipm_disk_ris", new_name="fdc_nd_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="kan_disk", new_name="fep_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="kan_disk_ris",
            new_name="fep_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="lev_disk", new_name="fos_nd200",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="lev_disk_ris",
            new_name="fos_nd200_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="lnz_disk", new_name="fox_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="lnz_disk_ris",
            new_name="fox_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="man_disk", new_name="geh_nd120",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="man_disk_ris",
            new_name="geh_nd120_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="mem_disk", new_name="gen_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="mem_disk_ris",
            new_name="gen_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="mfx_disk", new_name="imr_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="mfx_disk_ris",
            new_name="imr_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="mno_disk", new_name="ipm_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="mno_disk_ris",
            new_name="ipm_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="nal_disk", new_name="kan_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="nal_disk_ris",
            new_name="kan_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="net_disk", new_name="lnz_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="net_disk_ris",
            new_name="lnz_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="nit_disk", new_name="lvx_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="nit_disk_ris",
            new_name="lvx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="nor_disk", new_name="man_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="nor_disk_ris",
            new_name="man_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="nov_disk", new_name="mem_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="nov_disk_ris",
            new_name="mem_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="ofx_disk", new_name="mev_nd20",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="ofx_disk_ris",
            new_name="mev_nd20_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="oxa_disk", new_name="mfx_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="oxa_disk_ris",
            new_name="mfx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="pen_disk", new_name="mno_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="pen_disk_ris",
            new_name="mno_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="pip_disk", new_name="nal_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="pip_disk_ris",
            new_name="nal_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="pol_disk", new_name="net_nd30",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="pol_disk_ris",
            new_name="net_nd30_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="qda_disk", new_name="nit_nd300",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="qda_disk_ris",
            new_name="nit_nd300_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="rif_disk", new_name="nor_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="rif_disk_ris",
            new_name="nor_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="sam_disk", new_name="nov_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="sam_disk_ris",
            new_name="nov_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="spe_disk", new_name="ofx_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="spe_disk_ris",
            new_name="ofx_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="sth_disk", new_name="oxa_nd1",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="sth_disk_ris",
            new_name="oxa_nd1_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="str_disk", new_name="pen_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="str_disk_ris",
            new_name="pen_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="sxt_disk", new_name="pip_nd100",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="sxt_disk_ris",
            new_name="pip_nd100_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tcc_disk", new_name="plz_nd",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tcc_disk_ris", new_name="plz_nd_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tet_disk", new_name="pol_nd300",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="tet_disk_ris",
            new_name="pol_nd300_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tgc_disk", new_name="qda_nd15",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="tgc_disk_ris",
            new_name="qda_nd15_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tic_disk", new_name="rif_nd5",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="tic_disk_ris",
            new_name="rif_nd5_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tob_disk", new_name="sam_nd10",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="tob_disk_ris",
            new_name="sam_nd10_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="tzp_disk", new_name="spt_nd100",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="tzp_disk_ris",
            new_name="spt_nd100_ris",
        ),
        migrations.RenameField(
            model_name="sitediskresult", old_name="van_disk", new_name="sss_nd200",
        ),
        migrations.RenameField(
            model_name="sitediskresult",
            old_name="van_disk_ris",
            new_name="sss_nd200_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amc_mic", new_name="amc_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amc_mic_ris", new_name="amc_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amk_mic", new_name="amk_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amk_mic_ris", new_name="amk_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amp_mic", new_name="amp_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="amp_mic_ris", new_name="amp_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="atm_mic", new_name="amx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="atm_mic_ris", new_name="amx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="azm_mic", new_name="atm_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="azm_mic_ris", new_name="atm_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="caz_mic", new_name="azm_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="caz_mic_ris", new_name="azm_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cec_mic", new_name="caz_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cec_mic_ris", new_name="caz_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cep_mic", new_name="cec_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cep_mic_ris", new_name="cec_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cfm_mic", new_name="cep_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cfm_mic_ris", new_name="cep_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cfp_mic", new_name="cfm_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cfp_mic_ris", new_name="cfm_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="chl_mic", new_name="cfp_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="chl_mic_ris", new_name="cfp_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cip_mic", new_name="chl_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cip_mic_ris", new_name="chl_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cli_mic", new_name="cip_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cli_mic_ris", new_name="cip_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="clr_mic", new_name="cli_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="clr_mic_ris", new_name="cli_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="col_mic", new_name="clr_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="col_mic_ris", new_name="clr_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cro_mic", new_name="col_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cro_mic_ris", new_name="col_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ctx_mic", new_name="cro_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ctx_mic_ris", new_name="cro_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cxa_mic", new_name="ctx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="cxa_mic_ris", new_name="ctx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="czo_mic", new_name="cxa_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="czo_mic_ris", new_name="cxa_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dap_mic", new_name="cxm_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dap_mic_ris", new_name="cxm_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dor_mic", new_name="cza_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dor_mic_ris", new_name="cza_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dox_mic", new_name="czo_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="dox_mic_ris", new_name="czo_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ery_mic", new_name="czt_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ery_mic_ris", new_name="czt_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="etp_mic", new_name="dap_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="etp_mic_ris", new_name="dap_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="fep_mic", new_name="dor_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="fep_mic_ris", new_name="dor_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="fox_mic", new_name="dox_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="fox_mic_ris", new_name="dox_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="geh_mic", new_name="ery_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="geh_mic_ris", new_name="ery_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="gen_mic", new_name="etp_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="gen_mic_ris", new_name="etp_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ipm_mic", new_name="fdc_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ipm_mic_ris", new_name="fdc_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="kan_mic", new_name="fep_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="kan_mic_ris", new_name="fep_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="lev_mic", new_name="fos_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="lev_mic_ris", new_name="fos_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="lnz_mic", new_name="fox_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="lnz_mic_ris", new_name="fox_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="man_mic", new_name="geh_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="man_mic_ris", new_name="geh_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mem_mic", new_name="gen_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mem_mic_ris", new_name="gen_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mfx_mic", new_name="imr_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mfx_mic_ris", new_name="imr_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mno_mic", new_name="ipm_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="mno_mic_ris", new_name="ipm_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nal_mic", new_name="kan_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nal_mic_ris", new_name="kan_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="net_mic", new_name="lnz_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="net_mic_ris", new_name="lnz_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nit_mic", new_name="lvx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nit_mic_ris", new_name="lvx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nor_mic", new_name="man_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nor_mic_ris", new_name="man_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nov_mic", new_name="mem_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="nov_mic_ris", new_name="mem_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ofx_mic", new_name="mev_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="ofx_mic_ris", new_name="mev_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="oxa_mic", new_name="mfx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="oxa_mic_ris", new_name="mfx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pen_mic", new_name="mno_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pen_mic_ris", new_name="mno_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pip_mic", new_name="nal_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pip_mic_ris", new_name="nal_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pol_mic", new_name="net_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="pol_mic_ris", new_name="net_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="qda_mic", new_name="nit_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="qda_mic_ris", new_name="nit_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="rif_mic", new_name="nor_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="rif_mic_ris", new_name="nor_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sam_mic", new_name="nov_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sam_mic_ris", new_name="nov_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="spe_mic", new_name="ofx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="spe_mic_ris", new_name="ofx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sth_mic", new_name="oxa_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sth_mic_ris", new_name="oxa_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="str_mic", new_name="pen_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="str_mic_ris", new_name="pen_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sxt_mic", new_name="pip_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="sxt_mic_ris", new_name="pip_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tcc_mic", new_name="plz_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tcc_mic_ris", new_name="plz_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tet_mic", new_name="pol_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tet_mic_ris", new_name="pol_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tgc_mic", new_name="qda_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tgc_mic_ris", new_name="qda_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tic_mic", new_name="rif_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tic_mic_ris", new_name="rif_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tob_mic", new_name="sam_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tob_mic_ris", new_name="sam_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tzp_mic", new_name="spt_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="tzp_mic_ris", new_name="spt_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="van_mic", new_name="sss_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="van_mic_ris", new_name="sss_nm_ris",
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="sth_nd300",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="sth_nd300_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="str_nd10",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="str_nd10_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="sxt_nd1_2",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="sxt_nd1_2_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tcc_nd75",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tcc_nd75_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tcy_nd30",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tcy_nd30_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tgc_nd15",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tgc_nd15_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tic_nd75",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tic_nd75_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tob_nd10",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tob_nd10_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tzd_nd",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tzd_nd_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tzp_nd100",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="tzp_nd100_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="van_nd30",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitediskresult",
            name="van_nd30_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="sth_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="sth_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="str_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="str_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="sxt_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="sxt_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tcc_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tcc_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tcy_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tcy_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tgc_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tgc_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tic_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tic_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tob_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tob_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tzd_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tzd_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tzp_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="tzp_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="van_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalsitemicresult",
            name="van_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="sth_nd300",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="sth_nd300_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="str_nd10",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="str_nd10_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="sxt_nd1_2",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="sxt_nd1_2_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tcc_nd75",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tcc_nd75_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tcy_nd30",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tcy_nd30_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tgc_nd15",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tgc_nd15_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tic_nd75",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tic_nd75_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tob_nd10",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tob_nd10_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tzd_nd",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tzd_nd_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tzp_nd100",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="tzp_nd100_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="van_nd30",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitediskresult",
            name="van_nd30_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="sth_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="sth_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="str_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="str_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="sxt_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="sxt_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tcc_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tcc_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tcy_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tcy_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tgc_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tgc_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tic_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tic_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tob_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tob_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tzd_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tzd_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tzp_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="tzp_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="van_nm",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sitemicresult",
            name="van_nm_ris",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
