# Generated by Django 3.0.3 on 2022-06-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0003_batches_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='isolate_number',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='total_isolate_number',
        ),
    ]
