# Generated by Django 4.1 on 2024-06-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tat_sys", "0005_arsrldiskresult_amb_nd10_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arsrlmicresult", old_name="spx_nd5", new_name="spx_nm",
        ),
        migrations.RenameField(
            model_name="arsrlmicresult", old_name="spx_nd5_ris", new_name="spx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalarsrlmicresult",
            old_name="spx_nd5",
            new_name="spx_nm",
        ),
        migrations.RenameField(
            model_name="historicalarsrlmicresult",
            old_name="spx_nd5_ris",
            new_name="spx_nm_ris",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult", old_name="spx_nd5", new_name="spx_nm",
        ),
        migrations.RenameField(
            model_name="historicalsitemicresult",
            old_name="spx_nd5_ris",
            new_name="spx_nm_ris",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="spx_nd5", new_name="spx_nm",
        ),
        migrations.RenameField(
            model_name="sitemicresult", old_name="spx_nd5_ris", new_name="spx_nm_ris",
        ),
    ]
