# Generated by Django 3.0.3 on 2022-06-08 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0005_referred_sitepatieninformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='referred',
            name='created_by',
            field=models.TextField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x04BB92B0> <django.db.models.query_utils.DeferredAttribute object at 0x04BB92D0>', null=True),
        ),
    ]
