# Generated by Django 3.0.3 on 2022-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0006_auto_20220608_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred',
            name='created_by',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
