# Generated by Django 3.0.3 on 2022-06-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0007_auto_20220608_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred',
            name='updated_by',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sitepatieninformation',
            name='created_by',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sitepatieninformation',
            name='updated_by',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
