# Generated by Django 3.0.3 on 2022-06-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0008_auto_20220609_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepatieninformation',
            name='date_of_admission',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sitepatieninformation',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='SiteIsolteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_number', models.TextField(blank=True, default=None, null=True)),
                ('specimen_date', models.DateField(blank=True, default=None, null=True)),
                ('specimen_type', models.TextField(blank=True, default=None, null=True)),
                ('reason_for_referral', models.TextField(blank=True, default=None, null=True)),
                ('growth', models.TextField(blank=True, default=None, null=True)),
                ('urine_count', models.TextField(blank=True, default=None, null=True)),
                ('created_by', models.TextField(blank=True, default=None, null=True)),
                ('updated_by', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tat_sys.Referred')),
            ],
        ),
    ]
