# Generated by Django 3.0.3 on 2022-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0009_auto_20220613_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepatieninformation',
            name='patient_number',
            field=models.TextField(default=None, null=True),
        ),
    ]
