# Generated by Django 3.0.3 on 2022-06-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0010_auto_20220613_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhenotypicResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampc', models.TextField(blank=True, default=None, null=True)),
                ('esbl', models.TextField(blank=True, default=None, null=True)),
                ('carb', models.TextField(blank=True, default=None, null=True)),
                ('mbl', models.TextField(blank=True, default=None, null=True)),
                ('bl', models.TextField(blank=True, default=None, null=True)),
                ('mr', models.TextField(blank=True, default=None, null=True)),
                ('meca', models.TextField(blank=True, default=None, null=True)),
                ('icr', models.TextField(blank=True, default=None, null=True)),
                ('others', models.TextField(blank=True, default=None, null=True)),
                ('created_by', models.TextField(blank=True, default=None, null=True)),
                ('updated_by', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tat_sys.Referred')),
            ],
        ),
    ]
