# Generated by Django 3.0.3 on 2022-06-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0011_sitephenotypicresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOrganismResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_pre', models.TextField(blank=True, default=None, null=True)),
                ('org_code', models.TextField(blank=True, default=None, null=True)),
                ('org_site', models.TextField(blank=True, default=None, null=True)),
                ('site_post', models.TextField(blank=True, default=None, null=True)),
                ('created_by', models.TextField(blank=True, default=None, null=True)),
                ('updated_by', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tat_sys.Referred')),
            ],
        ),
    ]
