# Generated by Django 3.0.3 on 2022-06-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tat_sys', '0013_sitediskresult_sitemicresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemicresult',
            name='comments',
        ),
    ]
