from signal import default_int_handler
from tat_sys.models import Referred, SitePatienInformation, SiteIsolteInformation, SitePhenotypicResult, SiteOrganismResult, SiteDiskResult, SiteMicResult,ArsrlDiskResult, ArsrlMicResult, ArsrlOrganismInformation, ArsrlRecommendation
from datetime import datetime


def create_or_updated_referred_lab(request):
    uuid = check_variable_if_none(request.POST.get('referred_uuid'))
    referred = Referred.objects.filter(uuid=uuid).first()
    user = str(request.user.username)

    amc_nd20_ars = check_variable_if_none(request.POST.get('amc_nd20_ars'))
    amc_nd20_ris_ars = check_variable_if_none(request.POST.get('amc_nd20_ris_ars'))
    amk_nd30_ars = check_variable_if_none(request.POST.get('amk_nd30_ars'))
    amk_nd30_ris_ars = check_variable_if_none(request.POST.get('amk_nd30_ris_ars'))
    amp_nd10_ars = check_variable_if_none(request.POST.get('amp_nd10_ars'))
    amp_nd10_ris_ars = check_variable_if_none(request.POST.get('amp_nd10_ris_ars'))
    amx_nd30_ars = check_variable_if_none(request.POST.get('amx_nd30_ars'))
    amx_nd30_ris_ars = check_variable_if_none(request.POST.get('amx_nd30_ris_ars'))
    atm_nd30_ars = check_variable_if_none(request.POST.get('atm_nd30_ars'))
    atm_nd30_ris_ars = check_variable_if_none(request.POST.get('atm_nd30_ris_ars'))
    azm_nd15_ars = check_variable_if_none(request.POST.get('azm_nd15_ars'))
    azm_nd15_ris_ars = check_variable_if_none(request.POST.get('azm_nd15_ris_ars'))
    caz_nd30_ars = check_variable_if_none(request.POST.get('caz_nd30_ars'))
    caz_nd30_ris_ars = check_variable_if_none(request.POST.get('caz_nd30_ris_ars'))
    cec_nd30_ars = check_variable_if_none(request.POST.get('cec_nd30_ars'))
    cec_nd30_ris_ars = check_variable_if_none(request.POST.get('cec_nd30_ris_ars'))
    cep_nd30_ars = check_variable_if_none(request.POST.get('cep_nd30_ars'))
    cep_nd30_ris_ars = check_variable_if_none(request.POST.get('cep_nd30_ris_ars'))
    cfm_nd5_ars = check_variable_if_none(request.POST.get('cfm_nd5_ars'))
    cfm_nd5_ris_ars = check_variable_if_none(request.POST.get('cfm_nd5_ris_ars'))
    cfp_nd75_ars = check_variable_if_none(request.POST.get('cfp_nd75_ars'))
    cfp_nd75_ris_ars = check_variable_if_none(request.POST.get('cfp_nd75_ris_ars'))
    chl_nd30_ars = check_variable_if_none(request.POST.get('chl_nd30_ars'))
    chl_nd30_ris_ars = check_variable_if_none(request.POST.get('chl_nd30_ris_ars'))
    cip_nd5_ars = check_variable_if_none(request.POST.get('cip_nd5_ars'))
    cip_nd5_ris_ars = check_variable_if_none(request.POST.get('cip_nd5_ris_ars'))
    cli_nd2_ars = check_variable_if_none(request.POST.get('cli_nd2_ars'))
    cli_nd2_ris_ars = check_variable_if_none(request.POST.get('cli_nd2_ris_ars'))
    clr_nd15_ars = check_variable_if_none(request.POST.get('clr_nd15_ars'))
    clr_nd15_ris_ars = check_variable_if_none(request.POST.get('clr_nd15_ris_ars'))
    col_nd10_ars = check_variable_if_none(request.POST.get('col_nd10_ars'))
    col_nd10_ris_ars = check_variable_if_none(request.POST.get('col_nd10_ris_ars'))
    cro_nd30_ars = check_variable_if_none(request.POST.get('cro_nd30_ars'))
    cro_nd30_ris_ars = check_variable_if_none(request.POST.get('cro_nd30_ris_ars'))
    ctx_nd30_ars = check_variable_if_none(request.POST.get('ctx_nd30_ars'))
    ctx_nd30_ris_ars = check_variable_if_none(request.POST.get('ctx_nd30_ris_ars'))
    cxa_nd30_ars = check_variable_if_none(request.POST.get('cxa_nd30_ars'))
    cxa_nd30_ris_ars = check_variable_if_none(request.POST.get('cxa_nd30_ris_ars'))
    cxm_nd30_ars = check_variable_if_none(request.POST.get('cxm_nd30_ars'))
    cxm_nd30_ris_ars = check_variable_if_none(request.POST.get('cxm_nd30_ris_ars'))
    cza_nd30_ars = check_variable_if_none(request.POST.get('cza_nd30_ars'))
    cza_nd30_ris_ars = check_variable_if_none(request.POST.get('cza_nd30_ris_ars'))
    czo_nd30_ars = check_variable_if_none(request.POST.get('czo_nd30_ars'))
    czo_nd30_ris_ars = check_variable_if_none(request.POST.get('czo_nd30_ris_ars'))
    czt_nd30_ars = check_variable_if_none(request.POST.get('czt_nd30_ars'))
    czt_nd30_ris_ars = check_variable_if_none(request.POST.get('czt_nd30_ris_ars'))
    dap_nd30_ars = check_variable_if_none(request.POST.get('dap_nd30_ars'))
    dap_nd30_ris_ars = check_variable_if_none(request.POST.get('dap_nd30_ris_ars'))
    dor_nd10_ars = check_variable_if_none(request.POST.get('dor_nd10_ars'))
    dor_nd10_ris_ars = check_variable_if_none(request.POST.get('dor_nd10_ris_ars'))
    dox_nd30_ars = check_variable_if_none(request.POST.get('dox_nd30_ars'))
    dox_nd30_ris_ars = check_variable_if_none(request.POST.get('dox_nd30_ris_ars'))
    ery_nd15_ars = check_variable_if_none(request.POST.get('ery_nd15_ars'))
    ery_nd15_ris_ars = check_variable_if_none(request.POST.get('ery_nd15_ris_ars'))
    etp_nd10_ars = check_variable_if_none(request.POST.get('etp_nd10_ars'))
    etp_nd10_ris_ars = check_variable_if_none(request.POST.get('etp_nd10_ris_ars'))
    fdc_nd_ars = check_variable_if_none(request.POST.get('fdc_nd_ars'))
    fdc_nd_ris_ars = check_variable_if_none(request.POST.get('fdc_nd_ris_ars'))
    fep_nd30_ars = check_variable_if_none(request.POST.get('fep_nd30_ars'))
    fep_nd30_ris_ars = check_variable_if_none(request.POST.get('fep_nd30_ris_ars'))
    fos_nd200_ars = check_variable_if_none(request.POST.get('fos_nd200_ars'))
    fos_nd200_ris_ars = check_variable_if_none(request.POST.get('fos_nd200_ris_ars'))
    fox_nd30_ars = check_variable_if_none(request.POST.get('fox_nd30_ars'))
    fox_nd30_ris_ars = check_variable_if_none(request.POST.get('fox_nd30_ris_ars'))
    geh_nd120_ars = check_variable_if_none(request.POST.get('geh_nd120_ars'))
    geh_nd120_ris_ars = check_variable_if_none(request.POST.get('geh_nd120_ris_ars'))
    gen_nd10_ars = check_variable_if_none(request.POST.get('gen_nd10_ars'))
    gen_nd10_ris_ars = check_variable_if_none(request.POST.get('gen_nd10_ris_ars'))
    imr_nd10_ars = check_variable_if_none(request.POST.get('imr_nd10_ars'))
    imr_nd10_ris_ars = check_variable_if_none(request.POST.get('imr_nd10_ris_ars'))
    ipm_nd10_ars = check_variable_if_none(request.POST.get('ipm_nd10_ars'))
    ipm_nd10_ris_ars = check_variable_if_none(request.POST.get('ipm_nd10_ris_ars'))
    kan_nd30_ars = check_variable_if_none(request.POST.get('kan_nd30_ars'))
    kan_nd30_ris_ars = check_variable_if_none(request.POST.get('kan_nd30_ris_ars'))
    lnz_nd30_ars = check_variable_if_none(request.POST.get('lnz_nd30_ars'))
    lnz_nd30_ris_ars = check_variable_if_none(request.POST.get('lnz_nd30_ris_ars'))
    lvx_nd5_ars = check_variable_if_none(request.POST.get('lvx_nd5_ars'))
    lvx_nd5_ris_ars = check_variable_if_none(request.POST.get('lvx_nd5_ris_ars'))
    man_nd30_ars = check_variable_if_none(request.POST.get('man_nd30_ars'))
    man_nd30_ris_ars = check_variable_if_none(request.POST.get('man_nd30_ris_ars'))
    mem_nd10_ars = check_variable_if_none(request.POST.get('mem_nd10_ars'))
    mem_nd10_ris_ars = check_variable_if_none(request.POST.get('mem_nd10_ris_ars'))
    mev_nd20_ars = check_variable_if_none(request.POST.get('mev_nd20_ars'))
    mev_nd20_ris_ars = check_variable_if_none(request.POST.get('mev_nd20_ris_ars'))
    mfx_nd5_ars = check_variable_if_none(request.POST.get('mfx_nd5_ars'))
    mfx_nd5_ris_ars = check_variable_if_none(request.POST.get('mfx_nd5_ris_ars'))
    mno_nd30_ars = check_variable_if_none(request.POST.get('mno_nd30_ars'))
    mno_nd30_ris_ars = check_variable_if_none(request.POST.get('mno_nd30_ris_ars'))
    nal_nd30_ars = check_variable_if_none(request.POST.get('nal_nd30_ars'))
    nal_nd30_ris_ars = check_variable_if_none(request.POST.get('nal_nd30_ris_ars'))
    net_nd30_ars = check_variable_if_none(request.POST.get('net_nd30_ars'))
    net_nd30_ris_ars = check_variable_if_none(request.POST.get('net_nd30_ris_ars'))
    nit_nd300_ars = check_variable_if_none(request.POST.get('nit_nd300_ars'))
    nit_nd300_ris_ars = check_variable_if_none(request.POST.get('nit_nd300_ris_ars'))
    nor_nd10_ars = check_variable_if_none(request.POST.get('nor_nd10_ars'))
    nor_nd10_ris_ars = check_variable_if_none(request.POST.get('nor_nd10_ris'))
    nov_nd5_ars = check_variable_if_none(request.POST.get('nov_nd5_ars'))
    nov_nd5_ris_ars = check_variable_if_none(request.POST.get('nov_nd5_ris_ars'))
    ofx_nd5_ars = check_variable_if_none(request.POST.get('ofx_nd5_ars'))
    ofx_nd5_ris_ars = check_variable_if_none(request.POST.get('ofx_nd5_ris_ars'))
    oxa_nd1_ars = check_variable_if_none(request.POST.get('oxa_nd1_ars'))
    oxa_nd1_ris_ars = check_variable_if_none(request.POST.get('oxa_nd1_ris_ars'))
    pen_nd10_ars = check_variable_if_none(request.POST.get('pen_nd10_ars'))
    pen_nd10_ris_ars = check_variable_if_none(request.POST.get('pen_nd10_ris_ars'))
    pip_nd100_ars = check_variable_if_none(request.POST.get('pip_nd100_ars'))
    pip_nd100_ris_ars = check_variable_if_none(request.POST.get('pip_nd100_ris_ars'))
    plz_nd_ars = check_variable_if_none(request.POST.get('plz_nd_ars'))
    plz_nd_ris_ars = check_variable_if_none(request.POST.get('plz_nd_ris_ars'))
    pol_nd300_ars = check_variable_if_none(request.POST.get('pol_nd300_ars'))
    pol_nd300_ris_ars = check_variable_if_none(request.POST.get('pol_nd300_ris_ars'))
    qda_nd15_ars = check_variable_if_none(request.POST.get('qda_nd15_ars'))
    qda_nd15_ris_ars = check_variable_if_none(request.POST.get('qda_nd15_ris_ars'))
    rif_nd5_ars = check_variable_if_none(request.POST.get('rif_nd5_ars'))
    rif_nd5_ris_ars = check_variable_if_none(request.POST.get('rif_nd5_ris_ars'))
    sam_nd10_ars = check_variable_if_none(request.POST.get('sam_nd10_ars'))
    sam_nd10_ris_ars = check_variable_if_none(request.POST.get('sam_nd10_ris_ars'))
    spt_nd100_ars = check_variable_if_none(request.POST.get('spt_nd100_ars'))
    spt_nd100_ris_ars = check_variable_if_none(request.POST.get('spt_nd100_ris_ars'))
    sss_nd200_ars = check_variable_if_none(request.POST.get('sss_nd200_ars'))
    sss_nd200_ris_ars = check_variable_if_none(request.POST.get('sss_nd200_ris_ars'))
    sth_nd300_ars = check_variable_if_none(request.POST.get('sth_nd300_ars'))
    sth_nd300_ris_ars = check_variable_if_none(request.POST.get('sth_nd300_ris_ars'))
    str_nd10_ars = check_variable_if_none(request.POST.get('str_nd10_ars'))
    str_nd10_ris_ars = check_variable_if_none(request.POST.get('str_nd10_ris_ars'))
    sxt_nd1_2_ars = check_variable_if_none(request.POST.get('sxt_nd1_2_ars'))
    sxt_nd1_2_ris_ars = check_variable_if_none(request.POST.get('sxt_nd1_2_ris_ars'))
    tcc_nd75_ars = check_variable_if_none(request.POST.get('tcc_nd75_ars'))
    tcc_nd75_ris_ars = check_variable_if_none(request.POST.get('tcc_nd75_ris_ars'))
    tcy_nd30_ars = check_variable_if_none(request.POST.get('tcy_nd30_ars'))
    tcy_nd30_ris_ars = check_variable_if_none(request.POST.get('tcy_nd30_ris_ars'))
    tgc_nd15_ars = check_variable_if_none(request.POST.get('tgc_nd15_ars'))
    tgc_nd15_ris_ars = check_variable_if_none(request.POST.get('tgc_nd15_ris_ars'))
    tic_nd75_ars = check_variable_if_none(request.POST.get('tic_nd75_ars'))
    tic_nd75_ris_ars = check_variable_if_none(request.POST.get('tic_nd75_ris_ars'))
    tob_nd10_ars = check_variable_if_none(request.POST.get('tob_nd10_ars'))
    tob_nd10_ris_ars = check_variable_if_none(request.POST.get('tob_nd10_ris_ars'))
    tzd_nd_ars = check_variable_if_none(request.POST.get('tzd_nd_ars'))
    tzd_nd_ris_ars = check_variable_if_none(request.POST.get('tzd_nd_ris_ars'))
    tzp_nd100_ars = check_variable_if_none(request.POST.get('tzp_nd100_ars'))
    tzp_nd100_ris_ars = check_variable_if_none(request.POST.get('tzp_nd100_ris_ars'))
    van_nd30_ars = check_variable_if_none(request.POST.get('van_nd30_ars'))
    van_nd30_ris_ars = check_variable_if_none(request.POST.get('van_nd30_ris_ars'))


    amb_nd10_ars = check_variable_if_none(request.POST.get('amb_nd10_ars'))
    amb_nd10_ris_ars = check_variable_if_none(request.POST.get('amb_nd10_ris_ars'))
    cpt_nd30_ars = check_variable_if_none(request.POST.get('cpt_nd30_ars'))
    cpt_nd30_ris_ars = check_variable_if_none(request.POST.get('cpt_nd30_ris_ars'))
    fct_nd10_ars = check_variable_if_none(request.POST.get('fct_nd10_ars'))
    fct_nd10_ris_ars = check_variable_if_none(request.POST.get('fct_nd10_ris_ars'))
    pri_nd15_ars = check_variable_if_none(request.POST.get('pri_nd15_ars'))
    pri_nd15_ris_ars = check_variable_if_none(request.POST.get('pri_nd15_ris_ars'))
    spx_nd5_ars = check_variable_if_none(request.POST.get('spx_nd5_ars'))
    spx_nd5_ris_ars = check_variable_if_none(request.POST.get('spx_nd5_ris_ars'))
    tec_nd30_ars = check_variable_if_none(request.POST.get('tec_nd30_ars'))
    tec_nd30_ris_ars = check_variable_if_none(request.POST.get('tec_nd30_ris_ars'))
    tlt_nd15_ars = check_variable_if_none(request.POST.get('tlt_nd15_ars'))
    tlt_nd15_ris_ars = check_variable_if_none(request.POST.get('tlt_nd15_ris_ars'))
    comments = check_variable_if_none(request.POST.get('comments'))

    ars_save_disk = ArsrlDiskResult.objects.update_or_create(
        referred = referred,
        defaults={
            'amc_nd20' : amc_nd20_ars,
            'amc_nd20_ris' : amc_nd20_ris_ars,
            'amk_nd30' : amk_nd30_ars,
            'amk_nd30_ris' : amk_nd30_ris_ars,
            'amp_nd10' : amp_nd10_ars,
            'amp_nd10_ris' : amp_nd10_ris_ars,
            'amx_nd30' : amx_nd30_ars,
            'amx_nd30_ris' : amx_nd30_ris_ars,
            'atm_nd30' : atm_nd30_ars,
            'atm_nd30_ris' : atm_nd30_ris_ars,
            'azm_nd15' : azm_nd15_ars,
            'azm_nd15_ris' : azm_nd15_ris_ars,
            'caz_nd30' : caz_nd30_ars,
            'caz_nd30_ris' : caz_nd30_ris_ars,
            'cec_nd30' : cec_nd30_ars,
            'cec_nd30_ris' : cec_nd30_ris_ars,
            'cep_nd30' : cep_nd30_ars,
            'cep_nd30_ris' : cep_nd30_ris_ars,
            'cfm_nd5' : cfm_nd5_ars,
            'cfm_nd5_ris' : cfm_nd5_ris_ars,
            'cfp_nd75' : cfp_nd75_ars,
            'cfp_nd75_ris' : cfp_nd75_ris_ars,
            'chl_nd30' : chl_nd30_ars,
            'chl_nd30_ris' : chl_nd30_ris_ars,
            'cip_nd5' : cip_nd5_ars,
            'cip_nd5_ris' : cip_nd5_ris_ars,
            'cli_nd2' : cli_nd2_ars,
            'cli_nd2_ris' : cli_nd2_ris_ars,
            'clr_nd15' : clr_nd15_ars,
            'clr_nd15_ris' : clr_nd15_ris_ars,
            'col_nd10' : col_nd10_ars,
            'col_nd10_ris' : col_nd10_ris_ars,
            'cro_nd30' : cro_nd30_ars,
            'cro_nd30_ris' : cro_nd30_ris_ars,
            'ctx_nd30' : ctx_nd30_ars,
            'ctx_nd30_ris' : ctx_nd30_ris_ars,
            'cxa_nd30' : cxa_nd30_ars,
            'cxa_nd30_ris' : cxa_nd30_ris_ars,
            'cxm_nd30' : cxm_nd30_ars,
            'cxm_nd30_ris' : cxm_nd30_ris_ars,
            'cza_nd30' : cza_nd30_ars,
            'cza_nd30_ris' : cza_nd30_ris_ars,
            'czo_nd30' : czo_nd30_ars,
            'czo_nd30_ris' : czo_nd30_ris_ars,
            'czt_nd30' : czt_nd30_ars,
            'czt_nd30_ris' : czt_nd30_ris_ars,
            'dap_nd30' : dap_nd30_ars,
            'dap_nd30_ris' : dap_nd30_ris_ars,
            'dor_nd10' : dor_nd10_ars,
            'dor_nd10_ris' : dor_nd10_ris_ars,
            'dox_nd30' : dox_nd30_ars,
            'dox_nd30_ris' : dox_nd30_ris_ars,
            'ery_nd15' : ery_nd15_ars,
            'ery_nd15_ris' : ery_nd15_ris_ars,
            'etp_nd10' : etp_nd10_ars,
            'etp_nd10_ris' : etp_nd10_ris_ars,
            'fdc_nd' : fdc_nd_ars,
            'fdc_nd_ris' : fdc_nd_ris_ars,
            'fep_nd30' : fep_nd30_ars,
            'fep_nd30_ris' : fep_nd30_ris_ars,
            'fos_nd200' : fos_nd200_ars,
            'fos_nd200_ris' : fos_nd200_ris_ars,
            'fox_nd30' : fox_nd30_ars,
            'fox_nd30_ris' : fox_nd30_ris_ars,
            'geh_nd120' : geh_nd120_ars,
            'geh_nd120_ris' : geh_nd120_ris_ars,
            'gen_nd10' : gen_nd10_ars,
            'gen_nd10_ris' : gen_nd10_ris_ars,
            'imr_nd10' : imr_nd10_ars,
            'imr_nd10_ris' : imr_nd10_ris_ars,
            'ipm_nd10' : ipm_nd10_ars,
            'ipm_nd10_ris' : ipm_nd10_ris_ars,
            'kan_nd30' : kan_nd30_ars,
            'kan_nd30_ris' : kan_nd30_ris_ars,
            'lnz_nd30' : lnz_nd30_ars,
            'lnz_nd30_ris' : lnz_nd30_ris_ars,
            'lvx_nd5' : lvx_nd5_ars,
            'lvx_nd5_ris' : lvx_nd5_ris_ars,
            'man_nd30' : man_nd30_ars,
            'man_nd30_ris' : man_nd30_ris_ars,
            'mem_nd10' : mem_nd10_ars,
            'mem_nd10_ris' : mem_nd10_ris_ars,
            'mev_nd20' : mev_nd20_ars,
            'mev_nd20_ris' : mev_nd20_ris_ars,
            'mfx_nd5' : mfx_nd5_ars,
            'mfx_nd5_ris' : mfx_nd5_ris_ars,
            'mno_nd30' : mno_nd30_ars,
            'mno_nd30_ris' : mno_nd30_ris_ars,
            'nal_nd30' : nal_nd30_ars,
            'nal_nd30_ris' : nal_nd30_ris_ars,
            'net_nd30' : net_nd30_ars,
            'net_nd30_ris' : net_nd30_ris_ars,
            'nit_nd300' : nit_nd300_ars,
            'nit_nd300_ris' : nit_nd300_ris_ars,
            'nor_nd10' : nor_nd10_ars,
            'nor_nd10_ris' : nor_nd10_ris_ars,
            'nov_nd5' : nov_nd5_ars,
            'nov_nd5_ris' : nov_nd5_ris_ars,
            'ofx_nd5' : ofx_nd5_ars,
            'ofx_nd5_ris' : ofx_nd5_ris_ars,
            'oxa_nd1' : oxa_nd1_ars,
            'oxa_nd1_ris' : oxa_nd1_ris_ars,
            'pen_nd10' : pen_nd10_ars,
            'pen_nd10_ris' : pen_nd10_ris_ars,
            'pip_nd100' : pip_nd100_ars,
            'pip_nd100_ris' : pip_nd100_ris_ars,
            'plz_nd' : plz_nd_ars,
            'plz_nd_ris' : plz_nd_ris_ars,
            'pol_nd300' : pol_nd300_ars,
            'pol_nd300_ris' : pol_nd300_ris_ars,
            'qda_nd15' : qda_nd15_ars,
            'qda_nd15_ris' : qda_nd15_ris_ars,
            'rif_nd5' : rif_nd5_ars,
            'rif_nd5_ris' : rif_nd5_ris_ars,
            'sam_nd10' : sam_nd10_ars,
            'sam_nd10_ris' : sam_nd10_ris_ars,
            'spt_nd100' : spt_nd100_ars,
            'spt_nd100_ris' : spt_nd100_ris_ars,
            'sss_nd200' : sss_nd200_ars,
            'sss_nd200_ris' : sss_nd200_ris_ars,
            'sth_nd300' : sth_nd300_ars,
            'sth_nd300_ris' : sth_nd300_ris_ars,
            'str_nd10' : str_nd10_ars,
            'str_nd10_ris' : str_nd10_ris_ars,
            'sxt_nd1_2' : sxt_nd1_2_ars,
            'sxt_nd1_2_ris' : sxt_nd1_2_ris_ars,
            'tcc_nd75' : tcc_nd75_ars,
            'tcc_nd75_ris' : tcc_nd75_ris_ars,
            'tcy_nd30' : tcy_nd30_ars,
            'tcy_nd30_ris' : tcy_nd30_ris_ars,
            'tgc_nd15' : tgc_nd15_ars,
            'tgc_nd15_ris' : tgc_nd15_ris_ars,
            'tic_nd75' : tic_nd75_ars,
            'tic_nd75_ris' : tic_nd75_ris_ars,
            'tob_nd10' : tob_nd10_ars,
            'tob_nd10_ris' : tob_nd10_ris_ars,
            'tzd_nd' : tzd_nd_ars,
            'tzd_nd_ris' : tzd_nd_ris_ars,
            'tzp_nd100' : tzp_nd100_ars,
            'tzp_nd100_ris' : tzp_nd100_ris_ars,
            'van_nd30' : van_nd30_ars,
            'van_nd30_ris' : van_nd30_ris_ars,

            'amb_nd10' : amb_nd10_ars,
            'amb_nd10_ris' : amb_nd10_ris_ars,
            'cpt_nd30' : cpt_nd30_ars,
            'cpt_nd30_ris' : cpt_nd30_ris_ars,
            'fct_nd10' : fct_nd10_ars,
            'fct_nd10_ris' : fct_nd10_ris_ars,
            'pri_nd15' : pri_nd15_ars,
            'pri_nd15_ris' : pri_nd15_ris_ars,
            'spx_nd5' : spx_nd5_ars,
            'spx_nd5_ris' : spx_nd5_ris_ars,
            'tec_nd30' : tec_nd30_ars,
            'tec_nd30_ris' : tec_nd30_ris_ars,
            'tlt_nd15' : tlt_nd15_ars,
            'tlt_nd15_ris' : tlt_nd15_ris_ars,
            'comments' : comments, 
        }
    )
    
    
    amc_nm_ars = check_variable_if_none(request.POST.get('amc_nm_ars'))
    amc_nm_ris_ars = check_variable_if_none(request.POST.get('amc_nm_ris_ars'))
    amk_nm_ars = check_variable_if_none(request.POST.get('amk_nm_ars'))
    amk_nm_ris_ars = check_variable_if_none(request.POST.get('amk_nm_ris_ars'))
    amp_nm_ars = check_variable_if_none(request.POST.get('amp_nm_ars'))
    amp_nm_ris_ars = check_variable_if_none(request.POST.get('amp_nm_ris_ars'))
    amx_nm_ars = check_variable_if_none(request.POST.get('amx_nm_ars'))
    amx_nm_ris_ars = check_variable_if_none(request.POST.get('amx_nm_ris_ars'))
    atm_nm_ars = check_variable_if_none(request.POST.get('atm_nm_ars'))
    atm_nm_ris_ars = check_variable_if_none(request.POST.get('atm_nm_ris_ars'))
    azm_nm_ars = check_variable_if_none(request.POST.get('azm_nm_ars'))
    azm_nm_ris_ars = check_variable_if_none(request.POST.get('azm_nm_ris_ars'))
    caz_nm_ars = check_variable_if_none(request.POST.get('caz_nm_ars'))
    caz_nm_ris_ars = check_variable_if_none(request.POST.get('caz_nm_ris_ars'))
    cec_nm_ars = check_variable_if_none(request.POST.get('cec_nm_ars'))
    cec_nm_ris_ars = check_variable_if_none(request.POST.get('cec_nm_ris_ars'))
    cep_nm_ars = check_variable_if_none(request.POST.get('cep_nm_ars'))
    cep_nm_ris_ars = check_variable_if_none(request.POST.get('cep_nm_ris_ars'))
    cfm_nm_ars = check_variable_if_none(request.POST.get('cfm_nm_ars'))
    cfm_nm_ris_ars = check_variable_if_none(request.POST.get('cfm_nm_ris_ars'))
    cfp_nm_ars = check_variable_if_none(request.POST.get('cfp_nm_ars'))
    cfp_nm_ris_ars = check_variable_if_none(request.POST.get('cfp_nm_ris_ars'))
    chl_nm_ars = check_variable_if_none(request.POST.get('chl_nm_ars'))
    chl_nm_ris_ars = check_variable_if_none(request.POST.get('chl_nm_ris_ars'))
    cip_nm_ars = check_variable_if_none(request.POST.get('cip_nm_ars'))
    cip_nm_ris_ars = check_variable_if_none(request.POST.get('cip_nm_ris_ars'))
    cli_nm_ars = check_variable_if_none(request.POST.get('cli_nm_ars'))
    cli_nm_ris_ars = check_variable_if_none(request.POST.get('cli_nm_ris_ars'))
    clr_nm_ars = check_variable_if_none(request.POST.get('clr_nm_ars'))
    clr_nm_ris_ars = check_variable_if_none(request.POST.get('clr_nm_ris_ars'))
    col_nm_ars = check_variable_if_none(request.POST.get('col_nm_ars'))
    col_nm_ris_ars = check_variable_if_none(request.POST.get('col_nm_ris_ars'))
    cro_nm_ars = check_variable_if_none(request.POST.get('cro_nm_ars'))
    cro_nm_ris_ars = check_variable_if_none(request.POST.get('cro_nm_ris_ars'))
    ctx_nm_ars = check_variable_if_none(request.POST.get('ctx_nm_ars'))
    ctx_nm_ris_ars = check_variable_if_none(request.POST.get('ctx_nm_ris_ars'))
    cxa_nm_ars = check_variable_if_none(request.POST.get('cxa_nm_ars'))
    cxa_nm_ris_ars = check_variable_if_none(request.POST.get('cxa_nm_ris_ars'))
    cxm_nm_ars = check_variable_if_none(request.POST.get('cxm_nm_ars'))
    cxm_nm_ris_ars = check_variable_if_none(request.POST.get('cxm_nm_ris_ars'))
    cza_nm_ars = check_variable_if_none(request.POST.get('cza_nm_ars'))
    cza_nm_ris_ars = check_variable_if_none(request.POST.get('cza_nm_ris_ars'))
    czo_nm_ars = check_variable_if_none(request.POST.get('czo_nm_ars'))
    czo_nm_ris_ars = check_variable_if_none(request.POST.get('czo_nm_ris_ars'))
    czt_nm_ars = check_variable_if_none(request.POST.get('czt_nm_ars'))
    czt_nm_ris_ars = check_variable_if_none(request.POST.get('czt_nm_ris_ars'))
    dap_nm_ars = check_variable_if_none(request.POST.get('dap_nm_ars'))
    dap_nm_ris_ars = check_variable_if_none(request.POST.get('dap_nm_ris_ars'))
    dor_nm_ars = check_variable_if_none(request.POST.get('dor_nm_ars'))
    dor_nm_ris_ars = check_variable_if_none(request.POST.get('dor_nm_ris_ars'))
    dox_nm_ars = check_variable_if_none(request.POST.get('dox_nm_ars'))
    dox_nm_ris_ars = check_variable_if_none(request.POST.get('dox_nm_ris_ars'))
    ery_nm_ars = check_variable_if_none(request.POST.get('ery_nm_ars'))
    ery_nm_ris_ars = check_variable_if_none(request.POST.get('ery_nm_ris_ars'))
    etp_nm_ars = check_variable_if_none(request.POST.get('etp_nm_ars'))
    etp_nm_ris_ars = check_variable_if_none(request.POST.get('etp_nm_ris_ars'))
    fdc_nm_ars = check_variable_if_none(request.POST.get('fdc_nm_ars'))
    fdc_nm_ris_ars = check_variable_if_none(request.POST.get('fdc_nm_ris_ars'))
    fep_nm_ars = check_variable_if_none(request.POST.get('fep_nm_ars'))
    fep_nm_ris_ars = check_variable_if_none(request.POST.get('fep_nm_ris_ars'))
    fos_nm_ars = check_variable_if_none(request.POST.get('fos_nm_ars'))
    fos_nm_ris_ars = check_variable_if_none(request.POST.get('fos_nm_ris_ars'))
    fox_nm_ars = check_variable_if_none(request.POST.get('fox_nm_ars'))
    fox_nm_ris_ars = check_variable_if_none(request.POST.get('fox_nm_ris_ars'))
    geh_nm_ars = check_variable_if_none(request.POST.get('geh_nm_ars'))
    geh_nm_ris_ars = check_variable_if_none(request.POST.get('geh_nm_ris_ars'))
    gen_nm_ars = check_variable_if_none(request.POST.get('gen_nm_ars'))
    gen_nm_ris_ars = check_variable_if_none(request.POST.get('gen_nm_ris_ars'))
    imr_nm_ars = check_variable_if_none(request.POST.get('imr_nm_ars'))
    imr_nm_ris_ars = check_variable_if_none(request.POST.get('imr_nm_ris_ars'))
    ipm_nm_ars = check_variable_if_none(request.POST.get('ipm_nm_ars'))
    ipm_nm_ris_ars = check_variable_if_none(request.POST.get('ipm_nm_ris_ars'))
    kan_nm_ars = check_variable_if_none(request.POST.get('kan_nm_ars'))
    kan_nm_ris_ars = check_variable_if_none(request.POST.get('kan_nm_ris_ars'))
    lnz_nm_ars = check_variable_if_none(request.POST.get('lnz_nm_ars'))
    lnz_nm_ris_ars = check_variable_if_none(request.POST.get('lnz_nm_ris_ars'))
    lvx_nm_ars = check_variable_if_none(request.POST.get('lvx_nm_ars'))
    lvx_nm_ris_ars = check_variable_if_none(request.POST.get('lvx_nm_ris_ars'))
    man_nm_ars = check_variable_if_none(request.POST.get('man_nm_ars'))
    man_nm_ris_ars = check_variable_if_none(request.POST.get('man_nm_ris_ars'))
    mem_nm_ars = check_variable_if_none(request.POST.get('mem_nm_ars'))
    mem_nm_ris_ars = check_variable_if_none(request.POST.get('mem_nm_ris_ars'))
    mev_nm_ars = check_variable_if_none(request.POST.get('mev_nm_ars'))
    mev_nm_ris_ars = check_variable_if_none(request.POST.get('mev_nm_ris_ars'))
    mfx_nm_ars = check_variable_if_none(request.POST.get('mfx_nm_ars'))
    mfx_nm_ris_ars = check_variable_if_none(request.POST.get('mfx_nm_ris_ars'))
    mno_nm_ars = check_variable_if_none(request.POST.get('mno_nm_ars'))
    mno_nm_ris_ars = check_variable_if_none(request.POST.get('mno_nm_ris_ars'))
    nal_nm_ars = check_variable_if_none(request.POST.get('nal_nm_ars'))
    nal_nm_ris_ars = check_variable_if_none(request.POST.get('nal_nm_ris_ars'))
    net_nm_ars = check_variable_if_none(request.POST.get('net_nm_ars'))
    net_nm_ris_ars = check_variable_if_none(request.POST.get('net_nm_ris_ars'))
    nit_nm_ars = check_variable_if_none(request.POST.get('nit_nm_ars'))
    nit_nm_ris_ars = check_variable_if_none(request.POST.get('nit_nm_ris_ars'))
    nor_nm_ars = check_variable_if_none(request.POST.get('nor_nm_ars'))
    nor_nm_ris_ars = check_variable_if_none(request.POST.get('nor_nm_ris'))
    nov_nm_ars = check_variable_if_none(request.POST.get('nov_nm_ars'))
    nov_nm_ris_ars = check_variable_if_none(request.POST.get('nov_nm_ris_ars'))
    ofx_nm_ars = check_variable_if_none(request.POST.get('ofx_nm_ars'))
    ofx_nm_ris_ars = check_variable_if_none(request.POST.get('ofx_nm_ris_ars'))
    oxa_nm_ars = check_variable_if_none(request.POST.get('oxa_nm_ars'))
    oxa_nm_ris_ars = check_variable_if_none(request.POST.get('oxa_nm_ris_ars'))
    pen_nm_ars = check_variable_if_none(request.POST.get('pen_nm_ars'))
    pen_nm_ris_ars = check_variable_if_none(request.POST.get('pen_nm_ris_ars'))
    pip_nm_ars = check_variable_if_none(request.POST.get('pip_nm_ars'))
    pip_nm_ris_ars = check_variable_if_none(request.POST.get('pip_nm_ris_ars'))
    plz_nm_ars = check_variable_if_none(request.POST.get('plz_nm_ars'))
    plz_nm_ris_ars = check_variable_if_none(request.POST.get('plz_nm_ris_ars'))
    pol_nm_ars = check_variable_if_none(request.POST.get('pol_nm_ars'))
    pol_nm_ris_ars = check_variable_if_none(request.POST.get('pol_nm_ris_ars'))
    qda_nm_ars = check_variable_if_none(request.POST.get('qda_nm_ars'))
    qda_nm_ris_ars = check_variable_if_none(request.POST.get('qda_nm_ris_ars'))
    rif_nm_ars = check_variable_if_none(request.POST.get('rif_nm_ars'))
    rif_nm_ris_ars = check_variable_if_none(request.POST.get('rif_nm_ris_ars'))
    sam_nm_ars = check_variable_if_none(request.POST.get('sam_nm_ars'))
    sam_nm_ris_ars = check_variable_if_none(request.POST.get('sam_nm_ris_ars'))
    spt_nm_ars = check_variable_if_none(request.POST.get('spt_nm_ars'))
    spt_nm_ris_ars = check_variable_if_none(request.POST.get('spt_nm_ris_ars'))
    sss_nm_ars = check_variable_if_none(request.POST.get('sss_nm_ars'))
    sss_nm_ris_ars = check_variable_if_none(request.POST.get('sss_nm_ris_ars'))
    sth_nm_ars = check_variable_if_none(request.POST.get('sth_nm_ars'))
    sth_nm_ris_ars = check_variable_if_none(request.POST.get('sth_nm_ris_ars'))
    str_nm_ars = check_variable_if_none(request.POST.get('str_nm_ars'))
    str_nm_ris_ars = check_variable_if_none(request.POST.get('str_nm_ris_ars'))
    sxt_nm_ars = check_variable_if_none(request.POST.get('sxt_nm_ars'))
    sxt_nm_ris_ars = check_variable_if_none(request.POST.get('sxt_nm_ris_ars'))
    tcc_nm_ars = check_variable_if_none(request.POST.get('tcc_nm_ars'))
    tcc_nm_ris_ars = check_variable_if_none(request.POST.get('tcc_nm_ris_ars'))
    tcy_nm_ars = check_variable_if_none(request.POST.get('tcy_nm_ars'))
    tcy_nm_ris_ars = check_variable_if_none(request.POST.get('tcy_nm_ris_ars'))
    tgc_nm_ars = check_variable_if_none(request.POST.get('tgc_nm_ars'))
    tgc_nm_ris_ars = check_variable_if_none(request.POST.get('tgc_nm_ris_ars'))
    tic_nm_ars = check_variable_if_none(request.POST.get('tic_nm_ars'))
    tic_nm_ris_ars = check_variable_if_none(request.POST.get('tic_nm_ris_ars'))
    tob_nm_ars = check_variable_if_none(request.POST.get('tob_nm_ars'))
    tob_nm_ris_ars = check_variable_if_none(request.POST.get('tob_nm_ris_ars'))
    tzd_nm_ars = check_variable_if_none(request.POST.get('tzd_nm_ars'))
    tzd_nm_ris_ars = check_variable_if_none(request.POST.get('tzd_nm_ris_ars'))
    tzp_nm_ars = check_variable_if_none(request.POST.get('tzp_nm_ars'))
    tzp_nm_ris_ars = check_variable_if_none(request.POST.get('tzp_nm_ris_ars'))
    van_nm_ars = check_variable_if_none(request.POST.get('van_nm_ars'))
    van_nm_ris_ars = check_variable_if_none(request.POST.get('van_nm_ris_ars'))

    amb_nm_ars = check_variable_if_none(request.POST.get('amb_nm_ars'))
    amb_nm_ris_ars = check_variable_if_none(request.POST.get('amb_nm_ris_ars'))
    cpt_nm_ars = check_variable_if_none(request.POST.get('cpt_nm_ars'))
    cpt_nm_ris_ars = check_variable_if_none(request.POST.get('cpt_nm_ris_ars'))
    fct_nm_ars = check_variable_if_none(request.POST.get('fct_nm_ars'))
    fct_nm_ris_ars = check_variable_if_none(request.POST.get('fct_nm_ris_ars'))
    pri_nm_ars = check_variable_if_none(request.POST.get('pri_nm_ars'))
    pri_nm_ris_ars = check_variable_if_none(request.POST.get('pri_nm_ris_ars'))
    spx_nm_ars = check_variable_if_none(request.POST.get('spx_nm_ars'))
    spx_nm_ris_ars = check_variable_if_none(request.POST.get('spx_nm_ris_ars'))
    tec_nm_ars = check_variable_if_none(request.POST.get('tec_nm_ars'))
    tec_nm_ris_ars = check_variable_if_none(request.POST.get('tec_nm_ris_ars'))
    tlt_nm_ars = check_variable_if_none(request.POST.get('tlt_nm_ars'))
    tlt_nm_ris_ars = check_variable_if_none(request.POST.get('tlt_nm_ris_ars'))



    
    save_mic_ars = ArsrlMicResult.objects.update_or_create(
        referred = referred,
        defaults={
            'amc_nm' : amc_nm_ars,
            'amc_nm_ris' : amc_nm_ris_ars,
            'amk_nm' : amk_nm_ars,
            'amk_nm_ris' : amk_nm_ris_ars,
            'amp_nm' : amp_nm_ars,
            'amp_nm_ris' : amp_nm_ris_ars,
            'amx_nm' : amx_nm_ars,
            'amx_nm_ris' : amx_nm_ris_ars,
            'atm_nm' : atm_nm_ars,
            'atm_nm_ris' : atm_nm_ris_ars,
            'azm_nm' : azm_nm_ars,
            'azm_nm_ris' : azm_nm_ris_ars,
            'caz_nm' : caz_nm_ars,
            'caz_nm_ris' : caz_nm_ris_ars,
            'cec_nm' : cec_nm_ars,
            'cec_nm_ris' : cec_nm_ris_ars,
            'cep_nm' : cep_nm_ars,
            'cep_nm_ris' : cep_nm_ris_ars,
            'cfm_nm' : cfm_nm_ars,
            'cfm_nm_ris' : cfm_nm_ris_ars,
            'cfp_nm' : cfp_nm_ars,
            'cfp_nm_ris' : cfp_nm_ris_ars,
            'chl_nm' : chl_nm_ars,
            'chl_nm_ris' : chl_nm_ris_ars,
            'cip_nm' : cip_nm_ars,
            'cip_nm_ris' : cip_nm_ris_ars,
            'cli_nm' : cli_nm_ars,
            'cli_nm_ris' : cli_nm_ris_ars,
            'clr_nm' : clr_nm_ars,
            'clr_nm_ris' : clr_nm_ris_ars,
            'col_nm' : col_nm_ars,
            'col_nm_ris' : col_nm_ris_ars,
            'cro_nm' : cro_nm_ars,
            'cro_nm_ris' : cro_nm_ris_ars,
            'ctx_nm' : ctx_nm_ars,
            'ctx_nm_ris' : ctx_nm_ris_ars,
            'cxa_nm' : cxa_nm_ars,
            'cxa_nm_ris' : cxa_nm_ris_ars,
            'cxm_nm' : cxm_nm_ars,
            'cxm_nm_ris' : cxm_nm_ris_ars,
            'cza_nm' : cza_nm_ars,
            'cza_nm_ris' : cza_nm_ris_ars,
            'czo_nm' : czo_nm_ars,
            'czo_nm_ris' : czo_nm_ris_ars,
            'czt_nm' : czt_nm_ars,
            'czt_nm_ris' : czt_nm_ris_ars,
            'dap_nm' : dap_nm_ars,
            'dap_nm_ris' : dap_nm_ris_ars,
            'dor_nm' : dor_nm_ars,
            'dor_nm_ris' : dor_nm_ris_ars,
            'dox_nm' : dox_nm_ars,
            'dox_nm_ris' : dox_nm_ris_ars,
            'ery_nm' : ery_nm_ars,
            'ery_nm_ris' : ery_nm_ris_ars,
            'etp_nm' : etp_nm_ars,
            'etp_nm_ris' : etp_nm_ris_ars,
            'fdc_nm' : fdc_nm_ars,
            'fdc_nm_ris' : fdc_nm_ris_ars,
            'fep_nm' : fep_nm_ars,
            'fep_nm_ris' : fep_nm_ris_ars,
            'fos_nm' : fos_nm_ars,
            'fos_nm_ris' : fos_nm_ris_ars,
            'fox_nm' : fox_nm_ars,
            'fox_nm_ris' : fox_nm_ris_ars,
            'geh_nm' : geh_nm_ars,
            'geh_nm_ris' : geh_nm_ris_ars,
            'gen_nm' : gen_nm_ars,
            'gen_nm_ris' : gen_nm_ris_ars,
            'imr_nm' : imr_nm_ars,
            'imr_nm_ris' : imr_nm_ris_ars,
            'ipm_nm' : ipm_nm_ars,
            'ipm_nm_ris' : ipm_nm_ris_ars,
            'kan_nm' : kan_nm_ars,
            'kan_nm_ris' : kan_nm_ris_ars,
            'lnz_nm' : lnz_nm_ars,
            'lnz_nm_ris' : lnz_nm_ris_ars,
            'lvx_nm' : lvx_nm_ars,
            'lvx_nm_ris' : lvx_nm_ris_ars,
            'man_nm' : man_nm_ars,
            'man_nm_ris' : man_nm_ris_ars,
            'mem_nm' : mem_nm_ars,
            'mem_nm_ris' : mem_nm_ris_ars,
            'mev_nm' : mev_nm_ars,
            'mev_nm_ris' : mev_nm_ris_ars,
            'mfx_nm' : mfx_nm_ars,
            'mfx_nm_ris' : mfx_nm_ris_ars,
            'mno_nm' : mno_nm_ars,
            'mno_nm_ris' : mno_nm_ris_ars,
            'nal_nm' : nal_nm_ars,
            'nal_nm_ris' : nal_nm_ris_ars,
            'net_nm' : net_nm_ars,
            'net_nm_ris' : net_nm_ris_ars,
            'nit_nm' : nit_nm_ars,
            'nit_nm_ris' : nit_nm_ris_ars,
            'nor_nm' : nor_nm_ars,
            'nor_nm_ris' : nor_nm_ris_ars,
            'nov_nm' : nov_nm_ars,
            'nov_nm_ris' : nov_nm_ris_ars,
            'ofx_nm' : ofx_nm_ars,
            'ofx_nm_ris' : ofx_nm_ris_ars,
            'oxa_nm' : oxa_nm_ars,
            'oxa_nm_ris' : oxa_nm_ris_ars,
            'pen_nm' : pen_nm_ars,
            'pen_nm_ris' : pen_nm_ris_ars,
            'pip_nm' : pip_nm_ars,
            'pip_nm_ris' : pip_nm_ris_ars,
            'plz_nm' : plz_nm_ars,
            'plz_nm_ris' : plz_nm_ris_ars,
            'pol_nm' : pol_nm_ars,
            'pol_nm_ris' : pol_nm_ris_ars,
            'qda_nm' : qda_nm_ars,
            'qda_nm_ris' : qda_nm_ris_ars,
            'rif_nm' : rif_nm_ars,
            'rif_nm_ris' : rif_nm_ris_ars,
            'sam_nm' : sam_nm_ars,
            'sam_nm_ris' : sam_nm_ris_ars,
            'spt_nm' : spt_nm_ars,
            'spt_nm_ris' : spt_nm_ris_ars,
            'sss_nm' : sss_nm_ars,
            'sss_nm_ris' : sss_nm_ris_ars,
            'sth_nm' : sth_nm_ars,
            'sth_nm_ris' : sth_nm_ris_ars,
            'str_nm' : str_nm_ars,
            'str_nm_ris' : str_nm_ris_ars,
            'sxt_nm' : sxt_nm_ars,
            'sxt_nm_ris' : sxt_nm_ris_ars,
            'tcc_nm' : tcc_nm_ars,
            'tcc_nm_ris' : tcc_nm_ris_ars,
            'tcy_nm' : tcy_nm_ars,
            'tcy_nm_ris' : tcy_nm_ris_ars,
            'tgc_nm' : tgc_nm_ars,
            'tgc_nm_ris' : tgc_nm_ris_ars,
            'tic_nm' : tic_nm_ars,
            'tic_nm_ris' : tic_nm_ris_ars,
            'tob_nm' : tob_nm_ars,
            'tob_nm_ris' : tob_nm_ris_ars,
            'tzd_nm' : tzd_nm_ars,
            'tzd_nm_ris' : tzd_nm_ris_ars,
            'tzp_nm' : tzp_nm_ars,
            'tzp_nm_ris' : tzp_nm_ris_ars,
            'van_nm' : van_nm_ars,
            'van_nm_ris' : van_nm_ris_ars,

            'amb_nm' : amb_nm_ars,
            'amb_nm_ris' : amb_nm_ris_ars,
            'cpt_nm' : cpt_nm_ars,
            'cpt_nm_ris' : cpt_nm_ris_ars,
            'fct_nm' : fct_nm_ars,
            'fct_nm_ris' : fct_nm_ris_ars,
            'pri_nm' : pri_nm_ars,
            'pri_nm_ris' : pri_nm_ris_ars,
            'spx_nm' : spx_nm_ars,
            'spx_nm_ris' : spx_nm_ris_ars,
            'tec_nm' : tec_nm_ars,
            'tec_nm_ris' : tec_nm_ris_ars,
            'tlt_nm' : tlt_nm_ars,
            'tlt_nm_ris' : tlt_nm_ris_ars,
        }
    )
    
    ars_ampc = check_variable_if_none(request.POST.get('ars_ampc'))
    ars_esbl = check_variable_if_none(request.POST.get('ars_esbl'))
    ars_carb = check_variable_if_none(request.POST.get('ars_carb'))
    ars_ecim = check_variable_if_none(request.POST.get('ars_ecim'))
    ars_mcim = check_variable_if_none(request.POST.get('ars_mcim'))
    ars_ec_mcim = check_variable_if_none(request.POST.get('ars_ec_mcim'))
    ars_mbl = check_variable_if_none(request.POST.get('ars_mbl'))
    ars_bl = check_variable_if_none(request.POST.get('ars_bl'))
    ars_mr = check_variable_if_none(request.POST.get('ars_mr'))
    ars_meca = check_variable_if_none(request.POST.get('ars_meca'))
    ars_icr = check_variable_if_none(request.POST.get('ars_icr'))
    arsl_pre = check_variable_if_none(request.POST.get('arsl_pre'))
    ars_org_code = check_variable_if_none(request.POST.get('ars_org_code'))
    ars_org_name = check_variable_if_none(request.POST.get('ars_org_name'))
    arsrl_post = check_variable_if_none(request.POST.get('arsrl_post'))

    
    save_pheno_info_ars = ArsrlOrganismInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'ampc' : ars_ampc,
            'esbl' : ars_esbl,
            'carb' : ars_carb,
            'ecim' : ars_ecim,
            'mcim' : ars_mcim,
            'ec_mcim' : ars_ec_mcim,
            'mbl' : ars_mbl,
            'bl' : ars_bl,
            'mr' : ars_mr,
            'meca' : ars_meca,
            'icr' : ars_icr,
            # 'others' : ars_others,
            'arsl_pre' : arsl_pre,
            'org_code' : ars_org_code,
            'org_name' : ars_org_name,
            'arsrl_post' : arsrl_post,
        }
    )
    
    
    recommendation_code_ars = check_variable_if_none(request.POST.get('recommendation_code_ars'))
    recommendation_ars = check_variable_if_none(request.POST.get('recommendation_ars'))
    description_ars = check_variable_if_none(request.POST.get('description_ars'))

   
    
    save_recommendation_ars = ArsrlRecommendation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'recommendation_code' : recommendation_code_ars,
            'recommendation' : recommendation_ars,
            'description' : description_ars,
        }
    )

    return ars_save_disk

def create_or_updated_referred(request):
    date_of_birth = check_variable_if_none(request.POST.get('date_of_birth'))
    if date_of_birth:
        date_of_birth = datetime.strptime(date_of_birth, '%m/%d/%Y')
    else:
        date_of_birth = None
        
    date_of_admission = check_variable_if_none(request.POST.get('date_of_admission'))
    if date_of_admission:
        date_of_admission = datetime.strptime(date_of_admission, '%m/%d/%Y')
    else:
        date_of_admission = None
     
    uuid = check_variable_if_none(request.POST.get('referred_uuid'))
    patient_number = check_variable_if_none(request.POST.get('patient_number'))
    first_name = check_variable_if_none(request.POST.get('first_name'))
    middle_name = check_variable_if_none(request.POST.get('middle_name'))
    last_name = check_variable_if_none(request.POST.get('last_name'))
    diagnosis = check_variable_if_none(request.POST.get('diagnosis'))
    icd_10_code = check_variable_if_none(request.POST.get('icd_10_code'))
    sex = check_variable_if_none(request.POST.get('sex'))
    nosocomial = check_variable_if_none(request.POST.get('nosocomial'))
    ward = check_variable_if_none(request.POST.get('ward'))
    service_type = check_variable_if_none(request.POST.get('service_type'))

    referred = Referred.objects.filter(uuid=uuid).first()
    user = str(request.user.username)
    save_patient_info = SitePatienInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'patient_number' : patient_number,
            'first_name' : first_name,
            'middle_name' : middle_name,
            'last_name' : last_name,
            'date_of_birth' : date_of_birth,
            'sex' : sex,
            'date_of_admission' : date_of_admission,
            'nosocomial' : nosocomial,
            'diagnosis' : diagnosis,
            'icd_10_code' : icd_10_code,
            'ward' : ward,
            'service_type' : service_type,
        }
    )
    
    
    specimen_number = check_variable_if_none(request.POST.get('specimen_number'))
    specimen_date = check_variable_if_none(request.POST.get('specimen_date'))

    if specimen_date:
        specimen_date = datetime.strptime(specimen_date, '%m/%d/%Y')
    else:
        specimen_date = None
    specimen_type = check_variable_if_none(request.POST.get('specimen_type'))
    reason_for_referral = check_variable_if_none(request.POST.get('reason_for_referral'))
    growth = check_variable_if_none(request.POST.get('growth'))
    urine_count = check_variable_if_none(request.POST.get('urine_count'))

    
    
    
    save_isolate_info = SiteIsolteInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'specimen_number' : specimen_number,
            'specimen_date' : specimen_date,
            'specimen_type' : specimen_type,
            'reason_for_referral' : reason_for_referral,
            'growth' : growth,
            'urine_count' : urine_count,
        }
    )
    
    ampc = check_variable_if_none(request.POST.get('ampc'))
    esbl = check_variable_if_none(request.POST.get('esbl'))
    carb = check_variable_if_none(request.POST.get('carb'))
    mbl = check_variable_if_none(request.POST.get('mbl'))
    bl = check_variable_if_none(request.POST.get('bl'))
    mr = check_variable_if_none(request.POST.get('mr'))
    meca = check_variable_if_none(request.POST.get('meca'))
    icr = check_variable_if_none(request.POST.get('icr'))
    others = check_variable_if_none(request.POST.get('others'))

    
    save_pheno_info = SitePhenotypicResult.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'ampc' : ampc,
            'esbl' : esbl,
            'carb' : carb,
            'mbl' : mbl,
            'bl' : bl,
            'mr' : mr,
            'meca' : meca,
            'icr' : icr,
            'others' : others,
        }
    )
    
    site_pre = check_variable_if_none(request.POST.get('site_pre'))
    org_code = check_variable_if_none(request.POST.get('org_code'))
    org_site = check_variable_if_none(request.POST.get('org_site'))
    site_post = check_variable_if_none(request.POST.get('site_post'))

    
    save_org_info = SiteOrganismResult.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'site_pre' : site_pre,
            'org_code' : org_code,
            'org_site' : org_site,
            'site_post' : site_post,
        }
    )
    

    amc_nd20 = check_variable_if_none(request.POST.get('amc_nd20'))
    amc_nd20_ris = check_variable_if_none(request.POST.get('amc_nd20_ris'))
    amk_nd30 = check_variable_if_none(request.POST.get('amk_nd30'))
    amk_nd30_ris = check_variable_if_none(request.POST.get('amk_nd30_ris'))
    amp_nd10 = check_variable_if_none(request.POST.get('amp_nd10'))
    amp_nd10_ris = check_variable_if_none(request.POST.get('amp_nd10_ris'))
    amx_nd30 = check_variable_if_none(request.POST.get('amx_nd30'))
    amx_nd30_ris = check_variable_if_none(request.POST.get('amx_nd30_ris'))
    atm_nd30 = check_variable_if_none(request.POST.get('atm_nd30'))
    atm_nd30_ris = check_variable_if_none(request.POST.get('atm_nd30_ris'))
    azm_nd15 = check_variable_if_none(request.POST.get('azm_nd15'))
    azm_nd15_ris = check_variable_if_none(request.POST.get('azm_nd15_ris'))
    caz_nd30 = check_variable_if_none(request.POST.get('caz_nd30'))
    caz_nd30_ris = check_variable_if_none(request.POST.get('caz_nd30_ris'))
    cec_nd30 = check_variable_if_none(request.POST.get('cec_nd30'))
    cec_nd30_ris = check_variable_if_none(request.POST.get('cec_nd30_ris'))
    cep_nd30 = check_variable_if_none(request.POST.get('cep_nd30'))
    cep_nd30_ris = check_variable_if_none(request.POST.get('cep_nd30_ris'))
    cfm_nd5 = check_variable_if_none(request.POST.get('cfm_nd5'))
    cfm_nd5_ris = check_variable_if_none(request.POST.get('cfm_nd5_ris'))
    cfp_nd75 = check_variable_if_none(request.POST.get('cfp_nd75'))
    cfp_nd75_ris = check_variable_if_none(request.POST.get('cfp_nd75_ris'))
    chl_nd30 = check_variable_if_none(request.POST.get('chl_nd30'))
    chl_nd30_ris = check_variable_if_none(request.POST.get('chl_nd30_ris'))
    cip_nd5 = check_variable_if_none(request.POST.get('cip_nd5'))
    cip_nd5_ris = check_variable_if_none(request.POST.get('cip_nd5_ris'))
    cli_nd2 = check_variable_if_none(request.POST.get('cli_nd2'))
    cli_nd2_ris = check_variable_if_none(request.POST.get('cli_nd2_ris'))
    clr_nd15 = check_variable_if_none(request.POST.get('clr_nd15'))
    clr_nd15_ris = check_variable_if_none(request.POST.get('clr_nd15_ris'))
    col_nd10 = check_variable_if_none(request.POST.get('col_nd10'))
    col_nd10_ris = check_variable_if_none(request.POST.get('col_nd10_ris'))
    cro_nd30 = check_variable_if_none(request.POST.get('cro_nd30'))
    cro_nd30_ris = check_variable_if_none(request.POST.get('cro_nd30_ris'))
    ctx_nd30 = check_variable_if_none(request.POST.get('ctx_nd30'))
    ctx_nd30_ris = check_variable_if_none(request.POST.get('ctx_nd30_ris'))
    cxa_nd30 = check_variable_if_none(request.POST.get('cxa_nd30'))
    cxa_nd30_ris = check_variable_if_none(request.POST.get('cxa_nd30_ris'))
    cxm_nd30 = check_variable_if_none(request.POST.get('cxm_nd30'))
    cxm_nd30_ris = check_variable_if_none(request.POST.get('cxm_nd30_ris'))
    cza_nd30 = check_variable_if_none(request.POST.get('cza_nd30'))
    cza_nd30_ris = check_variable_if_none(request.POST.get('cza_nd30_ris'))
    czo_nd30 = check_variable_if_none(request.POST.get('czo_nd30'))
    czo_nd30_ris = check_variable_if_none(request.POST.get('czo_nd30_ris'))
    czt_nd30 = check_variable_if_none(request.POST.get('czt_nd30'))
    czt_nd30_ris = check_variable_if_none(request.POST.get('czt_nd30_ris'))
    dap_nd30 = check_variable_if_none(request.POST.get('dap_nd30'))
    dap_nd30_ris = check_variable_if_none(request.POST.get('dap_nd30_ris'))
    dor_nd10 = check_variable_if_none(request.POST.get('dor_nd10'))
    dor_nd10_ris = check_variable_if_none(request.POST.get('dor_nd10_ris'))
    dox_nd30 = check_variable_if_none(request.POST.get('dox_nd30'))
    dox_nd30_ris = check_variable_if_none(request.POST.get('dox_nd30_ris'))
    ery_nd15 = check_variable_if_none(request.POST.get('ery_nd15'))
    ery_nd15_ris = check_variable_if_none(request.POST.get('ery_nd15_ris'))
    etp_nd10 = check_variable_if_none(request.POST.get('etp_nd10'))
    etp_nd10_ris = check_variable_if_none(request.POST.get('etp_nd10_ris'))
    fdc_nd = check_variable_if_none(request.POST.get('fdc_nd'))
    fdc_nd_ris = check_variable_if_none(request.POST.get('fdc_nd_ris'))
    fep_nd30 = check_variable_if_none(request.POST.get('fep_nd30'))
    fep_nd30_ris = check_variable_if_none(request.POST.get('fep_nd30_ris'))
    fos_nd200 = check_variable_if_none(request.POST.get('fos_nd200'))
    fos_nd200_ris = check_variable_if_none(request.POST.get('fos_nd200_ris'))
    fox_nd30 = check_variable_if_none(request.POST.get('fox_nd30'))
    fox_nd30_ris = check_variable_if_none(request.POST.get('fox_nd30_ris'))
    geh_nd120 = check_variable_if_none(request.POST.get('geh_nd120'))
    geh_nd120_ris = check_variable_if_none(request.POST.get('geh_nd120_ris'))
    gen_nd10 = check_variable_if_none(request.POST.get('gen_nd10'))
    gen_nd10_ris = check_variable_if_none(request.POST.get('gen_nd10_ris'))
    imr_nd10 = check_variable_if_none(request.POST.get('imr_nd10'))
    imr_nd10_ris = check_variable_if_none(request.POST.get('imr_nd10_ris'))
    ipm_nd10 = check_variable_if_none(request.POST.get('ipm_nd10'))
    ipm_nd10_ris = check_variable_if_none(request.POST.get('ipm_nd10_ris'))
    kan_nd30 = check_variable_if_none(request.POST.get('kan_nd30'))
    kan_nd30_ris = check_variable_if_none(request.POST.get('kan_nd30_ris'))
    lnz_nd30 = check_variable_if_none(request.POST.get('lnz_nd30'))
    lnz_nd30_ris = check_variable_if_none(request.POST.get('lnz_nd30_ris'))
    lvx_nd5 = check_variable_if_none(request.POST.get('lvx_nd5'))
    lvx_nd5_ris = check_variable_if_none(request.POST.get('lvx_nd5_ris'))
    man_nd30 = check_variable_if_none(request.POST.get('man_nd30'))
    man_nd30_ris = check_variable_if_none(request.POST.get('man_nd30_ris'))
    mem_nd10 = check_variable_if_none(request.POST.get('mem_nd10'))
    mem_nd10_ris = check_variable_if_none(request.POST.get('mem_nd10_ris'))
    mev_nd20 = check_variable_if_none(request.POST.get('mev_nd20'))
    mev_nd20_ris = check_variable_if_none(request.POST.get('mev_nd20_ris'))
    mfx_nd5 = check_variable_if_none(request.POST.get('mfx_nd5'))
    mfx_nd5_ris = check_variable_if_none(request.POST.get('mfx_nd5_ris'))
    mno_nd30 = check_variable_if_none(request.POST.get('mno_nd30'))
    mno_nd30_ris = check_variable_if_none(request.POST.get('mno_nd30_ris'))
    nal_nd30 = check_variable_if_none(request.POST.get('nal_nd30'))
    nal_nd30_ris = check_variable_if_none(request.POST.get('nal_nd30_ris'))
    net_nd30 = check_variable_if_none(request.POST.get('net_nd30'))
    net_nd30_ris = check_variable_if_none(request.POST.get('net_nd30_ris'))
    nit_nd300 = check_variable_if_none(request.POST.get('nit_nd300'))
    nit_nd300_ris = check_variable_if_none(request.POST.get('nit_nd300_ris'))
    nor_nd10 = check_variable_if_none(request.POST.get('nor_nd10'))
    nor_nd10_ris = check_variable_if_none(request.POST.get('nor_nd10_ris'))
    nov_nd5 = check_variable_if_none(request.POST.get('nov_nd5'))
    nov_nd5_ris = check_variable_if_none(request.POST.get('nov_nd5_ris'))
    ofx_nd5 = check_variable_if_none(request.POST.get('ofx_nd5'))
    ofx_nd5_ris = check_variable_if_none(request.POST.get('ofx_nd5_ris'))
    oxa_nd1 = check_variable_if_none(request.POST.get('oxa_nd1'))
    oxa_nd1_ris = check_variable_if_none(request.POST.get('oxa_nd1_ris'))
    pen_nd10 = check_variable_if_none(request.POST.get('pen_nd10'))
    pen_nd10_ris = check_variable_if_none(request.POST.get('pen_nd10_ris'))
    pip_nd100 = check_variable_if_none(request.POST.get('pip_nd100'))
    pip_nd100_ris = check_variable_if_none(request.POST.get('pip_nd100_ris'))
    plz_nd = check_variable_if_none(request.POST.get('plz_nd'))
    plz_nd_ris = check_variable_if_none(request.POST.get('plz_nd_ris'))
    pol_nd300 = check_variable_if_none(request.POST.get('pol_nd300'))
    pol_nd300_ris = check_variable_if_none(request.POST.get('pol_nd300_ris'))
    qda_nd15 = check_variable_if_none(request.POST.get('qda_nd15'))
    qda_nd15_ris = check_variable_if_none(request.POST.get('qda_nd15_ris'))
    rif_nd5 = check_variable_if_none(request.POST.get('rif_nd5'))
    rif_nd5_ris = check_variable_if_none(request.POST.get('rif_nd5_ris'))
    sam_nd10 = check_variable_if_none(request.POST.get('sam_nd10'))
    sam_nd10_ris = check_variable_if_none(request.POST.get('sam_nd10_ris'))
    spt_nd100 = check_variable_if_none(request.POST.get('spt_nd100'))
    spt_nd100_ris = check_variable_if_none(request.POST.get('spt_nd100_ris'))
    sss_nd200 = check_variable_if_none(request.POST.get('sss_nd200'))
    sss_nd200_ris = check_variable_if_none(request.POST.get('sss_nd200_ris'))
    sth_nd300 = check_variable_if_none(request.POST.get('sth_nd300'))
    sth_nd300_ris = check_variable_if_none(request.POST.get('sth_nd300_ris'))
    str_nd10 = check_variable_if_none(request.POST.get('str_nd10'))
    str_nd10_ris = check_variable_if_none(request.POST.get('str_nd10_ris'))
    sxt_nd1_2 = check_variable_if_none(request.POST.get('sxt_nd1_2'))
    sxt_nd1_2_ris = check_variable_if_none(request.POST.get('sxt_nd1_2_ris'))
    tcc_nd75 = check_variable_if_none(request.POST.get('tcc_nd75'))
    tcc_nd75_ris = check_variable_if_none(request.POST.get('tcc_nd75_ris'))
    tcy_nd30 = check_variable_if_none(request.POST.get('tcy_nd30'))
    tcy_nd30_ris = check_variable_if_none(request.POST.get('tcy_nd30_ris'))
    tgc_nd15 = check_variable_if_none(request.POST.get('tgc_nd15'))
    tgc_nd15_ris = check_variable_if_none(request.POST.get('tgc_nd15_ris'))
    tic_nd75 = check_variable_if_none(request.POST.get('tic_nd75'))
    tic_nd75_ris = check_variable_if_none(request.POST.get('tic_nd75_ris'))
    tob_nd10 = check_variable_if_none(request.POST.get('tob_nd10'))
    tob_nd10_ris = check_variable_if_none(request.POST.get('tob_nd10_ris'))
    tzd_nd = check_variable_if_none(request.POST.get('tzd_nd'))
    tzd_nd_ris = check_variable_if_none(request.POST.get('tzd_nd_ris'))
    tzp_nd100 = check_variable_if_none(request.POST.get('tzp_nd100'))
    tzp_nd100_ris = check_variable_if_none(request.POST.get('tzp_nd100_ris'))
    van_nd30 = check_variable_if_none(request.POST.get('van_nd30'))
    van_nd30_ris = check_variable_if_none(request.POST.get('van_nd30_ris'))


    amb_nd10 = check_variable_if_none(request.POST.get('amb_nd10'))
    amb_nd10_ris = check_variable_if_none(request.POST.get('amb_nd10_ris'))
    cpt_nd30 = check_variable_if_none(request.POST.get('cpt_nd30'))
    cpt_nd30_ris = check_variable_if_none(request.POST.get('cpt_nd30_ris'))
    fct_nd10 = check_variable_if_none(request.POST.get('fct_nd10'))
    fct_nd10_ris = check_variable_if_none(request.POST.get('fct_nd10_ris'))
    pri_nd15 = check_variable_if_none(request.POST.get('pri_nd15'))
    pri_nd15_ris = check_variable_if_none(request.POST.get('pri_nd15_ris'))
    spx_nd5 = check_variable_if_none(request.POST.get('spx_nd5'))
    spx_nd5_ris = check_variable_if_none(request.POST.get('spx_nd5_ris'))
    tec_nd30 = check_variable_if_none(request.POST.get('tec_nd30'))
    tec_nd30_ris = check_variable_if_none(request.POST.get('tec_nd30_ris'))
    tlt_nd15 = check_variable_if_none(request.POST.get('tlt_nd15'))
    tlt_nd15_ris = check_variable_if_none(request.POST.get('tlt_nd15_ris'))
    comments = check_variable_if_none(request.POST['comments'])
    
    
    save_disk = SiteDiskResult.objects.update_or_create(
        referred = referred,
        defaults={
            'amc_nd20' : amc_nd20,
            'amc_nd20_ris' : amc_nd20_ris,
            'amk_nd30' : amk_nd30,
            'amk_nd30_ris' : amk_nd30_ris,
            'amp_nd10' : amp_nd10,
            'amp_nd10_ris' : amp_nd10_ris,
            'amx_nd30' : amx_nd30,
            'amx_nd30_ris' : amx_nd30_ris,
            'atm_nd30' : atm_nd30,
            'atm_nd30_ris' : atm_nd30_ris,
            'azm_nd15' : azm_nd15,
            'azm_nd15_ris' : azm_nd15_ris,
            'caz_nd30' : caz_nd30,
            'caz_nd30_ris' : caz_nd30_ris,
            'cec_nd30' : cec_nd30,
            'cec_nd30_ris' : cec_nd30_ris,
            'cep_nd30' : cep_nd30,
            'cep_nd30_ris' : cep_nd30_ris,
            'cfm_nd5' : cfm_nd5,
            'cfm_nd5_ris' : cfm_nd5_ris,
            'cfp_nd75' : cfp_nd75,
            'cfp_nd75_ris' : cfp_nd75_ris,
            'chl_nd30' : chl_nd30,
            'chl_nd30_ris' : chl_nd30_ris,
            'cip_nd5' : cip_nd5,
            'cip_nd5_ris' : cip_nd5_ris,
            'cli_nd2' : cli_nd2,
            'cli_nd2_ris' : cli_nd2_ris,
            'clr_nd15' : clr_nd15,
            'clr_nd15_ris' : clr_nd15_ris,
            'col_nd10' : col_nd10,
            'col_nd10_ris' : col_nd10_ris,
            'cro_nd30' : cro_nd30,
            'cro_nd30_ris' : cro_nd30_ris,
            'ctx_nd30' : ctx_nd30,
            'ctx_nd30_ris' : ctx_nd30_ris,
            'cxa_nd30' : cxa_nd30,
            'cxa_nd30_ris' : cxa_nd30_ris,
            'cxm_nd30' : cxm_nd30,
            'cxm_nd30_ris' : cxm_nd30_ris,
            'cza_nd30' : cza_nd30,
            'cza_nd30_ris' : cza_nd30_ris,
            'czo_nd30' : czo_nd30,
            'czo_nd30_ris' : czo_nd30_ris,
            'czt_nd30' : czt_nd30,
            'czt_nd30_ris' : czt_nd30_ris,
            'dap_nd30' : dap_nd30,
            'dap_nd30_ris' : dap_nd30_ris,
            'dor_nd10' : dor_nd10,
            'dor_nd10_ris' : dor_nd10_ris,
            'dox_nd30' : dox_nd30,
            'dox_nd30_ris' : dox_nd30_ris,
            'ery_nd15' : ery_nd15,
            'ery_nd15_ris' : ery_nd15_ris,
            'etp_nd10' : etp_nd10,
            'etp_nd10_ris' : etp_nd10_ris,
            'fdc_nd' : fdc_nd,
            'fdc_nd_ris' : fdc_nd_ris,
            'fep_nd30' : fep_nd30,
            'fep_nd30_ris' : fep_nd30_ris,
            'fos_nd200' : fos_nd200,
            'fos_nd200_ris' : fos_nd200_ris,
            'fox_nd30' : fox_nd30,
            'fox_nd30_ris' : fox_nd30_ris,
            'geh_nd120' : geh_nd120,
            'geh_nd120_ris' : geh_nd120_ris,
            'gen_nd10' : gen_nd10,
            'gen_nd10_ris' : gen_nd10_ris,
            'imr_nd10' : imr_nd10,
            'imr_nd10_ris' : imr_nd10_ris,
            'ipm_nd10' : ipm_nd10,
            'ipm_nd10_ris' : ipm_nd10_ris,
            'kan_nd30' : kan_nd30,
            'kan_nd30_ris' : kan_nd30_ris,
            'lnz_nd30' : lnz_nd30,
            'lnz_nd30_ris' : lnz_nd30_ris,
            'lvx_nd5' : lvx_nd5,
            'lvx_nd5_ris' : lvx_nd5_ris,
            'man_nd30' : man_nd30,
            'man_nd30_ris' : man_nd30_ris,
            'mem_nd10' : mem_nd10,
            'mem_nd10_ris' : mem_nd10_ris,
            'mev_nd20' : mev_nd20,
            'mev_nd20_ris' : mev_nd20_ris,
            'mfx_nd5' : mfx_nd5,
            'mfx_nd5_ris' : mfx_nd5_ris,
            'mno_nd30' : mno_nd30,
            'mno_nd30_ris' : mno_nd30_ris,
            'nal_nd30' : nal_nd30,
            'nal_nd30_ris' : nal_nd30_ris,
            'net_nd30' : net_nd30,
            'net_nd30_ris' : net_nd30_ris,
            'nit_nd300' : nit_nd300,
            'nit_nd300_ris' : nit_nd300_ris,
            'nor_nd10' : nor_nd10,
            'nor_nd10_ris' : nor_nd10_ris,
            'nov_nd5' : nov_nd5,
            'nov_nd5_ris' : nov_nd5_ris,
            'ofx_nd5' : ofx_nd5,
            'ofx_nd5_ris' : ofx_nd5_ris,
            'oxa_nd1' : oxa_nd1,
            'oxa_nd1_ris' : oxa_nd1_ris,
            'pen_nd10' : pen_nd10,
            'pen_nd10_ris' : pen_nd10_ris,
            'pip_nd100' : pip_nd100,
            'pip_nd100_ris' : pip_nd100_ris,
            'plz_nd' : plz_nd,
            'plz_nd_ris' : plz_nd_ris,
            'pol_nd300' : pol_nd300,
            'pol_nd300_ris' : pol_nd300_ris,
            'qda_nd15' : qda_nd15,
            'qda_nd15_ris' : qda_nd15_ris,
            'rif_nd5' : rif_nd5,
            'rif_nd5_ris' : rif_nd5_ris,
            'sam_nd10' : sam_nd10,
            'sam_nd10_ris' : sam_nd10_ris,
            'spt_nd100' : spt_nd100,
            'spt_nd100_ris' : spt_nd100_ris,
            'sss_nd200' : sss_nd200,
            'sss_nd200_ris' : sss_nd200_ris,
            'sth_nd300' : sth_nd300,
            'sth_nd300_ris' : sth_nd300_ris,
            'str_nd10' : str_nd10,
            'str_nd10_ris' : str_nd10_ris,
            'sxt_nd1_2' : sxt_nd1_2,
            'sxt_nd1_2_ris' : sxt_nd1_2_ris,
            'tcc_nd75' : tcc_nd75,
            'tcc_nd75_ris' : tcc_nd75_ris,
            'tcy_nd30' : tcy_nd30,
            'tcy_nd30_ris' : tcy_nd30_ris,
            'tgc_nd15' : tgc_nd15,
            'tgc_nd15_ris' : tgc_nd15_ris,
            'tic_nd75' : tic_nd75,
            'tic_nd75_ris' : tic_nd75_ris,
            'tob_nd10' : tob_nd10,
            'tob_nd10_ris' : tob_nd10_ris,
            'tzd_nd' : tzd_nd,
            'tzd_nd_ris' : tzd_nd_ris,
            'tzp_nd100' : tzp_nd100,
            'tzp_nd100_ris' : tzp_nd100_ris,
            'van_nd30' : van_nd30,
            'van_nd30_ris' : van_nd30_ris,

            'amb_nd10' : amb_nd10,
            'amb_nd10_ris' : amb_nd10_ris,
            'cpt_nd30' : cpt_nd30,
            'cpt_nd30_ris' : cpt_nd30_ris,
            'fct_nd10' : fct_nd10,
            'fct_nd10_ris' : fct_nd10_ris,
            'pri_nd15' : pri_nd15,
            'pri_nd15_ris' : pri_nd15_ris,
            'spx_nd5' : spx_nd5,
            'spx_nd5_ris' : spx_nd5_ris,
            'tec_nd30' : tec_nd30,
            'tec_nd30_ris' : tec_nd30_ris,
            'tlt_nd15' : tlt_nd15,
            'tlt_nd15_ris' : tlt_nd15_ris,
            'comments' : comments, 
        }
    )
    
    
    amc_nm = check_variable_if_none(request.POST.get('amc_nm'))
    amc_nm_ris = check_variable_if_none(request.POST.get('amc_nm_ris'))
    amk_nm = check_variable_if_none(request.POST.get('amk_nm'))
    amk_nm_ris = check_variable_if_none(request.POST.get('amk_nm_ris'))
    amp_nm = check_variable_if_none(request.POST.get('amp_nm'))
    amp_nm_ris = check_variable_if_none(request.POST.get('amp_nm_ris'))
    amx_nm = check_variable_if_none(request.POST.get('amx_nm'))
    amx_nm_ris = check_variable_if_none(request.POST.get('amx_nm_ris'))
    atm_nm = check_variable_if_none(request.POST.get('atm_nm'))
    atm_nm_ris = check_variable_if_none(request.POST.get('atm_nm_ris'))
    azm_nm = check_variable_if_none(request.POST.get('azm_nm'))
    azm_nm_ris = check_variable_if_none(request.POST.get('azm_nm_ris'))
    caz_nm = check_variable_if_none(request.POST.get('caz_nm'))
    caz_nm_ris = check_variable_if_none(request.POST.get('caz_nm_ris'))
    cec_nm = check_variable_if_none(request.POST.get('cec_nm'))
    cec_nm_ris = check_variable_if_none(request.POST.get('cec_nm_ris'))
    cep_nm = check_variable_if_none(request.POST.get('cep_nm'))
    cep_nm_ris = check_variable_if_none(request.POST.get('cep_nm_ris'))
    cfm_nm = check_variable_if_none(request.POST.get('cfm_nm'))
    cfm_nm_ris = check_variable_if_none(request.POST.get('cfm_nm_ris'))
    cfp_nm = check_variable_if_none(request.POST.get('cfp_nm'))
    cfp_nm_ris = check_variable_if_none(request.POST.get('cfp_nm_ris'))
    chl_nm = check_variable_if_none(request.POST.get('chl_nm'))
    chl_nm_ris = check_variable_if_none(request.POST.get('chl_nm_ris'))
    cip_nm = check_variable_if_none(request.POST.get('cip_nm'))
    cip_nm_ris = check_variable_if_none(request.POST.get('cip_nm_ris'))
    cli_nm = check_variable_if_none(request.POST.get('cli_nm'))
    cli_nm_ris = check_variable_if_none(request.POST.get('cli_nm_ris'))
    clr_nm = check_variable_if_none(request.POST.get('clr_nm'))
    clr_nm_ris = check_variable_if_none(request.POST.get('clr_nm_ris'))
    col_nm = check_variable_if_none(request.POST.get('col_nm'))
    col_nm_ris = check_variable_if_none(request.POST.get('col_nm_ris'))
    cro_nm = check_variable_if_none(request.POST.get('cro_nm'))
    cro_nm_ris = check_variable_if_none(request.POST.get('cro_nm_ris'))
    ctx_nm = check_variable_if_none(request.POST.get('ctx_nm'))
    ctx_nm_ris = check_variable_if_none(request.POST.get('ctx_nm_ris'))
    cxa_nm = check_variable_if_none(request.POST.get('cxa_nm'))
    cxa_nm_ris = check_variable_if_none(request.POST.get('cxa_nm_ris'))
    cxm_nm = check_variable_if_none(request.POST.get('cxm_nm'))
    cxm_nm_ris = check_variable_if_none(request.POST.get('cxm_nm_ris'))
    cza_nm = check_variable_if_none(request.POST.get('cza_nm'))
    cza_nm_ris = check_variable_if_none(request.POST.get('cza_nm_ris'))
    czo_nm = check_variable_if_none(request.POST.get('czo_nm'))
    czo_nm_ris = check_variable_if_none(request.POST.get('czo_nm_ris'))
    czt_nm = check_variable_if_none(request.POST.get('czt_nm'))
    czt_nm_ris = check_variable_if_none(request.POST.get('czt_nm_ris'))
    dap_nm = check_variable_if_none(request.POST.get('dap_nm'))
    dap_nm_ris = check_variable_if_none(request.POST.get('dap_nm_ris'))
    dor_nm = check_variable_if_none(request.POST.get('dor_nm'))
    dor_nm_ris = check_variable_if_none(request.POST.get('dor_nm_ris'))
    dox_nm = check_variable_if_none(request.POST.get('dox_nm'))
    dox_nm_ris = check_variable_if_none(request.POST.get('dox_nm_ris'))
    ery_nm = check_variable_if_none(request.POST.get('ery_nm'))
    ery_nm_ris = check_variable_if_none(request.POST.get('ery_nm_ris'))
    etp_nm = check_variable_if_none(request.POST.get('etp_nm'))
    etp_nm_ris = check_variable_if_none(request.POST.get('etp_nm_ris'))
    fdc_nm = check_variable_if_none(request.POST.get('fdc_nm'))
    fdc_nm_ris = check_variable_if_none(request.POST.get('fdc_nm_ris'))
    fep_nm = check_variable_if_none(request.POST.get('fep_nm'))
    fep_nm_ris = check_variable_if_none(request.POST.get('fep_nm_ris'))
    fos_nm = check_variable_if_none(request.POST.get('fos_nm'))
    fos_nm_ris = check_variable_if_none(request.POST.get('fos_nm_ris'))
    fox_nm = check_variable_if_none(request.POST.get('fox_nm'))
    fox_nm_ris = check_variable_if_none(request.POST.get('fox_nm_ris'))
    geh_nm = check_variable_if_none(request.POST.get('geh_nm'))
    geh_nm_ris = check_variable_if_none(request.POST.get('geh_nm_ris'))
    gen_nm = check_variable_if_none(request.POST.get('gen_nm'))
    gen_nm_ris = check_variable_if_none(request.POST.get('gen_nm_ris'))
    imr_nm = check_variable_if_none(request.POST.get('imr_nm'))
    imr_nm_ris = check_variable_if_none(request.POST.get('imr_nm_ris'))
    ipm_nm = check_variable_if_none(request.POST.get('ipm_nm'))
    ipm_nm_ris = check_variable_if_none(request.POST.get('ipm_nm_ris'))
    kan_nm = check_variable_if_none(request.POST.get('kan_nm'))
    kan_nm_ris = check_variable_if_none(request.POST.get('kan_nm_ris'))
    lnz_nm = check_variable_if_none(request.POST.get('lnz_nm'))
    lnz_nm_ris = check_variable_if_none(request.POST.get('lnz_nm_ris'))
    lvx_nm = check_variable_if_none(request.POST.get('lvx_nm'))
    lvx_nm_ris = check_variable_if_none(request.POST.get('lvx_nm_ris'))
    man_nm = check_variable_if_none(request.POST.get('man_nm'))
    man_nm_ris = check_variable_if_none(request.POST.get('man_nm_ris'))
    mem_nm = check_variable_if_none(request.POST.get('mem_nm'))
    mem_nm_ris = check_variable_if_none(request.POST.get('mem_nm_ris'))
    mev_nm = check_variable_if_none(request.POST.get('mev_nm'))
    mev_nm_ris = check_variable_if_none(request.POST.get('mev_nm_ris'))
    mfx_nm = check_variable_if_none(request.POST.get('mfx_nm'))
    mfx_nm_ris = check_variable_if_none(request.POST.get('mfx_nm_ris'))
    mno_nm = check_variable_if_none(request.POST.get('mno_nm'))
    mno_nm_ris = check_variable_if_none(request.POST.get('mno_nm_ris'))
    nal_nm = check_variable_if_none(request.POST.get('nal_nm'))
    nal_nm_ris = check_variable_if_none(request.POST.get('nal_nm_ris'))
    net_nm = check_variable_if_none(request.POST.get('net_nm'))
    net_nm_ris = check_variable_if_none(request.POST.get('net_nm_ris'))
    nit_nm = check_variable_if_none(request.POST.get('nit_nm'))
    nit_nm_ris = check_variable_if_none(request.POST.get('nit_nm_ris'))
    nor_nm = check_variable_if_none(request.POST.get('nor_nm'))
    nor_nm_ris = check_variable_if_none(request.POST.get('nor_nm_ris'))
    nov_nm = check_variable_if_none(request.POST.get('nov_nm'))
    nov_nm_ris = check_variable_if_none(request.POST.get('nov_nm_ris'))
    ofx_nm = check_variable_if_none(request.POST.get('ofx_nm'))
    ofx_nm_ris = check_variable_if_none(request.POST.get('ofx_nm_ris'))
    oxa_nm = check_variable_if_none(request.POST.get('oxa_nm'))
    oxa_nm_ris = check_variable_if_none(request.POST.get('oxa_nm_ris'))
    pen_nm = check_variable_if_none(request.POST.get('pen_nm'))
    pen_nm_ris = check_variable_if_none(request.POST.get('pen_nm_ris'))
    pip_nm = check_variable_if_none(request.POST.get('pip_nm'))
    pip_nm_ris = check_variable_if_none(request.POST.get('pip_nm_ris'))
    plz_nm = check_variable_if_none(request.POST.get('plz_nm'))
    plz_nm_ris = check_variable_if_none(request.POST.get('plz_nm_ris'))
    pol_nm = check_variable_if_none(request.POST.get('pol_nm'))
    pol_nm_ris = check_variable_if_none(request.POST.get('pol_nm_ris'))
    qda_nm = check_variable_if_none(request.POST.get('qda_nm'))
    qda_nm_ris = check_variable_if_none(request.POST.get('qda_nm_ris'))
    rif_nm = check_variable_if_none(request.POST.get('rif_nm'))
    rif_nm_ris = check_variable_if_none(request.POST.get('rif_nm_ris'))
    sam_nm = check_variable_if_none(request.POST.get('sam_nm'))
    sam_nm_ris = check_variable_if_none(request.POST.get('sam_nm_ris'))
    spt_nm = check_variable_if_none(request.POST.get('spt_nm'))
    spt_nm_ris = check_variable_if_none(request.POST.get('spt_nm_ris'))
    sss_nm = check_variable_if_none(request.POST.get('sss_nm'))
    sss_nm_ris = check_variable_if_none(request.POST.get('sss_nm_ris'))
    sth_nm = check_variable_if_none(request.POST.get('sth_nm'))
    sth_nm_ris = check_variable_if_none(request.POST.get('sth_nm_ris'))
    str_nm = check_variable_if_none(request.POST.get('str_nm'))
    str_nm_ris = check_variable_if_none(request.POST.get('str_nm_ris'))
    sxt_nm = check_variable_if_none(request.POST.get('sxt_nm'))
    sxt_nm_ris = check_variable_if_none(request.POST.get('sxt_nm_ris'))
    tcc_nm = check_variable_if_none(request.POST.get('tcc_nm'))
    tcc_nm_ris = check_variable_if_none(request.POST.get('tcc_nm_ris'))
    tcy_nm = check_variable_if_none(request.POST.get('tcy_nm'))
    tcy_nm_ris = check_variable_if_none(request.POST.get('tcy_nm_ris'))
    tgc_nm = check_variable_if_none(request.POST.get('tgc_nm'))
    tgc_nm_ris = check_variable_if_none(request.POST.get('tgc_nm_ris'))
    tic_nm = check_variable_if_none(request.POST.get('tic_nm'))
    tic_nm_ris = check_variable_if_none(request.POST.get('tic_nm_ris'))
    tob_nm = check_variable_if_none(request.POST.get('tob_nm'))
    tob_nm_ris = check_variable_if_none(request.POST.get('tob_nm_ris'))
    tzd_nm = check_variable_if_none(request.POST.get('tzd_nm'))
    tzd_nm_ris = check_variable_if_none(request.POST.get('tzd_nm_ris'))
    tzp_nm = check_variable_if_none(request.POST.get('tzp_nm'))
    tzp_nm_ris = check_variable_if_none(request.POST.get('tzp_nm_ris'))
    van_nm = check_variable_if_none(request.POST.get('van_nm'))
    van_nm_ris = check_variable_if_none(request.POST.get('van_nm_ris'))

    amb_nm = check_variable_if_none(request.POST.get('amb_nm'))
    amb_nm_ris = check_variable_if_none(request.POST.get('amb_nm_ris'))
    cpt_nm = check_variable_if_none(request.POST.get('cpt_nm'))
    cpt_nm_ris = check_variable_if_none(request.POST.get('cpt_nm_ris'))
    fct_nm = check_variable_if_none(request.POST.get('fct_nm'))
    fct_nm_ris = check_variable_if_none(request.POST.get('fct_nm_ris'))
    pri_nm = check_variable_if_none(request.POST.get('pri_nm'))
    pri_nm_ris = check_variable_if_none(request.POST.get('pri_nm_ris'))
    spx_nm = check_variable_if_none(request.POST.get('spx_nm'))
    spx_nm_ris = check_variable_if_none(request.POST.get('spx_nm_ris'))
    tec_nm = check_variable_if_none(request.POST.get('tec_nm'))
    tec_nm_ris = check_variable_if_none(request.POST.get('tec_nm_ris'))
    tlt_nm = check_variable_if_none(request.POST.get('tlt_nm'))
    tlt_nm_ris = check_variable_if_none(request.POST.get('tlt_nm_ris'))
    
    
    save_mic = SiteMicResult.objects.update_or_create(
        referred = referred,
        defaults={
            'amc_nm' : amc_nm,
            'amc_nm_ris' : amc_nm_ris,
            'amk_nm' : amk_nm,
            'amk_nm_ris' : amk_nm_ris,
            'amp_nm' : amp_nm,
            'amp_nm_ris' : amp_nm_ris,
            'amx_nm' : amx_nm,
            'amx_nm_ris' : amx_nm_ris,
            'atm_nm' : atm_nm,
            'atm_nm_ris' : atm_nm_ris,
            'azm_nm' : azm_nm,
            'azm_nm_ris' : azm_nm_ris,
            'caz_nm' : caz_nm,
            'caz_nm_ris' : caz_nm_ris,
            'cec_nm' : cec_nm,
            'cec_nm_ris' : cec_nm_ris,
            'cep_nm' : cep_nm,
            'cep_nm_ris' : cep_nm_ris,
            'cfm_nm' : cfm_nm,
            'cfm_nm_ris' : cfm_nm_ris,
            'cfp_nm' : cfp_nm,
            'cfp_nm_ris' : cfp_nm_ris,
            'chl_nm' : chl_nm,
            'chl_nm_ris' : chl_nm_ris,
            'cip_nm' : cip_nm,
            'cip_nm_ris' : cip_nm_ris,
            'cli_nm' : cli_nm,
            'cli_nm_ris' : cli_nm_ris,
            'clr_nm' : clr_nm,
            'clr_nm_ris' : clr_nm_ris,
            'col_nm' : col_nm,
            'col_nm_ris' : col_nm_ris,
            'cro_nm' : cro_nm,
            'cro_nm_ris' : cro_nm_ris,
            'ctx_nm' : ctx_nm,
            'ctx_nm_ris' : ctx_nm_ris,
            'cxa_nm' : cxa_nm,
            'cxa_nm_ris' : cxa_nm_ris,
            'cxm_nm' : cxm_nm,
            'cxm_nm_ris' : cxm_nm_ris,
            'cza_nm' : cza_nm,
            'cza_nm_ris' : cza_nm_ris,
            'czo_nm' : czo_nm,
            'czo_nm_ris' : czo_nm_ris,
            'czt_nm' : czt_nm,
            'czt_nm_ris' : czt_nm_ris,
            'dap_nm' : dap_nm,
            'dap_nm_ris' : dap_nm_ris,
            'dor_nm' : dor_nm,
            'dor_nm_ris' : dor_nm_ris,
            'dox_nm' : dox_nm,
            'dox_nm_ris' : dox_nm_ris,
            'ery_nm' : ery_nm,
            'ery_nm_ris' : ery_nm_ris,
            'etp_nm' : etp_nm,
            'etp_nm_ris' : etp_nm_ris,
            'fdc_nm' : fdc_nm,
            'fdc_nm_ris' : fdc_nm_ris,
            'fep_nm' : fep_nm,
            'fep_nm_ris' : fep_nm_ris,
            'fos_nm' : fos_nm,
            'fos_nm_ris' : fos_nm_ris,
            'fox_nm' : fox_nm,
            'fox_nm_ris' : fox_nm_ris,
            'geh_nm' : geh_nm,
            'geh_nm_ris' : geh_nm_ris,
            'gen_nm' : gen_nm,
            'gen_nm_ris' : gen_nm_ris,
            'imr_nm' : imr_nm,
            'imr_nm_ris' : imr_nm_ris,
            'ipm_nm' : ipm_nm,
            'ipm_nm_ris' : ipm_nm_ris,
            'kan_nm' : kan_nm,
            'kan_nm_ris' : kan_nm_ris,
            'lnz_nm' : lnz_nm,
            'lnz_nm_ris' : lnz_nm_ris,
            'lvx_nm' : lvx_nm,
            'lvx_nm_ris' : lvx_nm_ris,
            'man_nm' : man_nm,
            'man_nm_ris' : man_nm_ris,
            'mem_nm' : mem_nm,
            'mem_nm_ris' : mem_nm_ris,
            'mev_nm' : mev_nm,
            'mev_nm_ris' : mev_nm_ris,
            'mfx_nm' : mfx_nm,
            'mfx_nm_ris' : mfx_nm_ris,
            'mno_nm' : mno_nm,
            'mno_nm_ris' : mno_nm_ris,
            'nal_nm' : nal_nm,
            'nal_nm_ris' : nal_nm_ris,
            'net_nm' : net_nm,
            'net_nm_ris' : net_nm_ris,
            'nit_nm' : nit_nm,
            'nit_nm_ris' : nit_nm_ris,
            'nor_nm' : nor_nm,
            'nor_nm_ris' : nor_nm_ris,
            'nov_nm' : nov_nm,
            'nov_nm_ris' : nov_nm_ris,
            'ofx_nm' : ofx_nm,
            'ofx_nm_ris' : ofx_nm_ris,
            'oxa_nm' : oxa_nm,
            'oxa_nm_ris' : oxa_nm_ris,
            'pen_nm' : pen_nm,
            'pen_nm_ris' : pen_nm_ris,
            'pip_nm' : pip_nm,
            'pip_nm_ris' : pip_nm_ris,
            'plz_nm' : plz_nm,
            'plz_nm_ris' : plz_nm_ris,
            'pol_nm' : pol_nm,
            'pol_nm_ris' : pol_nm_ris,
            'qda_nm' : qda_nm,
            'qda_nm_ris' : qda_nm_ris,
            'rif_nm' : rif_nm,
            'rif_nm_ris' : rif_nm_ris,
            'sam_nm' : sam_nm,
            'sam_nm_ris' : sam_nm_ris,
            'spt_nm' : spt_nm,
            'spt_nm_ris' : spt_nm_ris,
            'sss_nm' : sss_nm,
            'sss_nm_ris' : sss_nm_ris,
            'sth_nm' : sth_nm,
            'sth_nm_ris' : sth_nm_ris,
            'str_nm' : str_nm,
            'str_nm_ris' : str_nm_ris,
            'sxt_nm' : sxt_nm,
            'sxt_nm_ris' : sxt_nm_ris,
            'tcc_nm' : tcc_nm,
            'tcc_nm_ris' : tcc_nm_ris,
            'tcy_nm' : tcy_nm,
            'tcy_nm_ris' : tcy_nm_ris,
            'tgc_nm' : tgc_nm,
            'tgc_nm_ris' : tgc_nm_ris,
            'tic_nm' : tic_nm,
            'tic_nm_ris' : tic_nm_ris,
            'tob_nm' : tob_nm,
            'tob_nm_ris' : tob_nm_ris,
            'tzd_nm' : tzd_nm,
            'tzd_nm_ris' : tzd_nm_ris,
            'tzp_nm' : tzp_nm,
            'tzp_nm_ris' : tzp_nm_ris,
            'van_nm' : van_nm,
            'van_nm_ris' : van_nm_ris,

            'amb_nm' : amb_nm,
            'amb_nm_ris' : amb_nm_ris,
            'cpt_nm' : cpt_nm,
            'cpt_nm_ris' : cpt_nm_ris,
            'fct_nm' : fct_nm,
            'fct_nm_ris' : fct_nm_ris,
            'pri_nm' : pri_nm,
            'pri_nm_ris' : pri_nm_ris,
            'spx_nm' : spx_nm,
            'spx_nm_ris' : spx_nm_ris,
            'tec_nm' : tec_nm,
            'tec_nm_ris' : tec_nm_ris,
            'tlt_nm' : tlt_nm,
            'tlt_nm_ris' : tlt_nm_ris,
        }
    )

    
    
    
    return save_patient_info




def check_variable_if_none(var):
    if var:
        return var
    elif var != '':
        return None
    else:
        return None
    

# def check_variable_if_none(var):
#     if var is not None:
#         return var
#     else:
#         return None