from signal import default_int_handler
from tat_sys.models import Referred, SitePatienInformation, SiteIsolteInformation, SitePhenotypicResult, SiteOrganismResult, SiteDiskResult, SiteMicResult,ArsrlDiskResult, ArsrlMicResult, ArsrlOrganismInformation, ArsrlRecommendation
from datetime import datetime

def create_or_updated_referred(request):
    date_of_birth = check_variable_if_none(request.POST['date_of_birth'])
    if date_of_birth:
        date_of_birth = datetime.strptime(date_of_birth, '%m/%d/%Y')
    else:
        date_of_birth = None
        
    date_of_admission = check_variable_if_none(request.POST['date_of_admission'])
    if date_of_admission:
        date_of_admission = datetime.strptime(date_of_admission, '%m/%d/%Y')
    else:
        date_of_admission = None
     
    uuid = check_variable_if_none(request.POST['referred_uuid'])
    patient_number = check_variable_if_none(request.POST['patient_number'])
    first_name = check_variable_if_none(request.POST['first_name'])
    middle_name = check_variable_if_none(request.POST['middle_name'])
    last_name = check_variable_if_none(request.POST['last_name'])
    diagnosis = check_variable_if_none(request.POST['diagnosis'])
    icd_10_code = check_variable_if_none(request.POST['icd_10_code'])
    sex = check_variable_if_none(request.POST['sex'])
    nosocomial = check_variable_if_none(request.POST['nosocomial'])
    ward = check_variable_if_none(request.POST['ward'])
    service_type = check_variable_if_none(request.POST['service_type'])
    print(sex)
    referred = Referred.objects.filter(uuid=uuid).first()
    user = str(request.user.first_name) + ' ' + str(request.user.last_name)
    save_patient_info = SitePatienInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'patient_number' : patient_number,
            'first_name' : first_name,
            'middle_name' : middle_name,
            'last_name' : last_name,
            'date_of_birth' : date_of_birth,
            'sex' : sex,
            'date_of_admission' : date_of_admission,
            'nosocomial' : nosocomial,
            'diagnosis' : diagnosis,
            'icd_10_code' : icd_10_code,
            'ward' : ward,
            'service_type' : service_type,
            'updated_by' : user,
        }
    )
    
    
    specimen_number = check_variable_if_none(request.POST['specimen_number'])
    specimen_date = check_variable_if_none(request.POST['specimen_date'])
    if specimen_date:
        specimen_date = datetime.strptime(specimen_date, '%m/%d/%Y')
    else:
        specimen_date = None
    specimen_type = check_variable_if_none(request.POST['specimen_type'])
    reason_for_referral = check_variable_if_none(request.POST['reason_for_referral'])
    growth = check_variable_if_none(request.POST['growth'])
    urine_count = check_variable_if_none(request.POST['urine_count'])
    
    
    
    save_isolate_info = SiteIsolteInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'specimen_number' : specimen_number,
            'specimen_date' : specimen_date,
            'specimen_type' : specimen_type,
            'reason_for_referral' : reason_for_referral,
            'growth' : growth,
            'urine_count' : urine_count,
            'updated_by' : user
        }
    )
    
    ampc = check_variable_if_none(request.POST['ampc'])
    esbl = check_variable_if_none(request.POST['esbl'])
    carb = check_variable_if_none(request.POST['carb'])
    mbl = check_variable_if_none(request.POST['mbl'])
    bl = check_variable_if_none(request.POST['bl'])
    mr = check_variable_if_none(request.POST['mr'])
    meca = check_variable_if_none(request.POST['meca'])
    icr = check_variable_if_none(request.POST['icr'])
    others = check_variable_if_none(request.POST['others'])
    
    save_pheno_info = SitePhenotypicResult.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'ampc' : ampc,
            'esbl' : esbl,
            'carb' : carb,
            'mbl' : mbl,
            'bl' : bl,
            'mr' : mr,
            'meca' : meca,
            'icr' : icr,
            'others' : others,
            'updated_by' : user
        }
    )
    
    site_pre = check_variable_if_none(request.POST['site_pre'])
    org_code = check_variable_if_none(request.POST['org_code'])
    org_site = check_variable_if_none(request.POST['org_site'])
    site_post = check_variable_if_none(request.POST['site_post'])
    
    save_org_info = SiteOrganismResult.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'site_pre' : site_pre,
            'org_code' : org_code,
            'org_site' : org_site,
            'site_post' : site_post,
            'updated_by' : user
        }
    )
    
    
    amk_disk = check_variable_if_none(request.POST['amk_disk'])
    amk_disk_ris = check_variable_if_none(request.POST['amk_disk_ris'])
    amc_disk = check_variable_if_none(request.POST['amc_disk'])
    amc_disk_ris = check_variable_if_none(request.POST['amc_disk_ris'])
    amp_disk = check_variable_if_none(request.POST['amp_disk'])
    amp_disk_ris = check_variable_if_none(request.POST['amp_disk_ris'])
    sam_disk = check_variable_if_none(request.POST['sam_disk'])
    sam_disk_ris = check_variable_if_none(request.POST['sam_disk_ris'])
    atm_disk = check_variable_if_none(request.POST['atm_disk'])
    atm_disk_ris = check_variable_if_none(request.POST['atm_disk_ris'])
    azm_disk = check_variable_if_none(request.POST['azm_disk'])
    azm_disk_ris = check_variable_if_none(request.POST['azm_disk_ris'])
    cec_disk = check_variable_if_none(request.POST['cec_disk'])
    cec_disk_ris = check_variable_if_none(request.POST['cec_disk_ris'])
    man_disk = check_variable_if_none(request.POST['man_disk'])
    man_disk_ris = check_variable_if_none(request.POST['man_disk_ris'])
    czo_disk = check_variable_if_none(request.POST['czo_disk'])
    czo_disk_ris = check_variable_if_none(request.POST['czo_disk_ris'])
    fep_disk = check_variable_if_none(request.POST['fep_disk'])
    fep_disk_ris = check_variable_if_none(request.POST['fep_disk_ris'])
    cfm_disk = check_variable_if_none(request.POST['cfm_disk'])
    cfm_disk_ris = check_variable_if_none(request.POST['cfm_disk_ris'])
    cfp_disk = check_variable_if_none(request.POST['cfp_disk'])
    cfp_disk_ris = check_variable_if_none(request.POST['cfp_disk_ris'])
    ctx_disk = check_variable_if_none(request.POST['ctx_disk'])
    ctx_disk_ris = check_variable_if_none(request.POST['ctx_disk_ris'])
    fox_disk = check_variable_if_none(request.POST['fox_disk'])
    fox_disk_ris = check_variable_if_none(request.POST['fox_disk_ris'])
    caz_disk = check_variable_if_none(request.POST['caz_disk'])
    caz_disk_ris = check_variable_if_none(request.POST['caz_disk_ris'])
    cro_disk = check_variable_if_none(request.POST['cro_disk'])
    cro_disk_ris = check_variable_if_none(request.POST['cro_disk_ris'])
    cxa_disk = check_variable_if_none(request.POST['cxa_disk'])
    cxa_disk_ris = check_variable_if_none(request.POST['cxa_disk_ris'])
    cep_disk = check_variable_if_none(request.POST['cep_disk'])
    cep_disk_ris = check_variable_if_none(request.POST['cep_disk_ris'])
    chl_disk = check_variable_if_none(request.POST['chl_disk'])
    chl_disk_ris = check_variable_if_none(request.POST['chl_disk_ris'])
    cip_disk = check_variable_if_none(request.POST['cip_disk'])
    cip_disk_ris = check_variable_if_none(request.POST['cip_disk_ris'])
    clr_disk = check_variable_if_none(request.POST['clr_disk'])
    clr_disk_ris = check_variable_if_none(request.POST['clr_disk_ris'])
    cli_disk = check_variable_if_none(request.POST['cli_disk'])
    cli_disk_ris = check_variable_if_none(request.POST['cli_disk_ris'])
    sxt_disk = check_variable_if_none(request.POST['sxt_disk'])
    sxt_disk_ris = check_variable_if_none(request.POST['sxt_disk_ris'])
    ery_disk = check_variable_if_none(request.POST['ery_disk'])
    ery_disk_ris = check_variable_if_none(request.POST['ery_disk_ris'])
    gen_disk = check_variable_if_none(request.POST['gen_disk'])
    gen_disk_ris = check_variable_if_none(request.POST['gen_disk_ris'])
    ipm_disk = check_variable_if_none(request.POST['ipm_disk'])
    ipm_disk_ris = check_variable_if_none(request.POST['ipm_disk_ris'])
    kan_disk = check_variable_if_none(request.POST['kan_disk'])
    kan_disk_ris = check_variable_if_none(request.POST['kan_disk_ris'])
    lev_disk = check_variable_if_none(request.POST['lev_disk'])
    lev_disk_ris = check_variable_if_none(request.POST['lev_disk_ris'])
    nal_disk = check_variable_if_none(request.POST['nal_disk'])
    nal_disk_ris = check_variable_if_none(request.POST['nal_disk_ris'])
    net_disk = check_variable_if_none(request.POST['net_disk'])
    net_disk_ris = check_variable_if_none(request.POST['net_disk_ris'])
    nit_disk = check_variable_if_none(request.POST['nit_disk'])
    nit_disk_ris = check_variable_if_none(request.POST['nit_disk_ris'])
    nor_disk = check_variable_if_none(request.POST['nor_disk'])
    nor_disk_ris = check_variable_if_none(request.POST['nor_disk_ris'])
    ofx_disk = check_variable_if_none(request.POST['ofx_disk'])
    ofx_disk_ris = check_variable_if_none(request.POST['ofx_disk_ris'])
    oxa_disk = check_variable_if_none(request.POST['oxa_disk'])
    oxa_disk_ris = check_variable_if_none(request.POST['oxa_disk_ris'])
    pen_disk = check_variable_if_none(request.POST['pen_disk'])
    pen_disk_ris = check_variable_if_none(request.POST['pen_disk_ris'])
    pip_disk = check_variable_if_none(request.POST['pip_disk'])
    pip_disk_ris = check_variable_if_none(request.POST['pip_disk_ris'])
    rif_disk = check_variable_if_none(request.POST['rif_disk'])
    rif_disk_ris = check_variable_if_none(request.POST['rif_disk_ris'])
    spe_disk = check_variable_if_none(request.POST['spe_disk'])
    spe_disk_ris = check_variable_if_none(request.POST['spe_disk_ris'])
    str_disk = check_variable_if_none(request.POST['str_disk'])
    str_disk_ris = check_variable_if_none(request.POST['str_disk_ris'])
    tet_disk = check_variable_if_none(request.POST['tet_disk'])
    tet_disk_ris = check_variable_if_none(request.POST['tet_disk_ris'])
    tic_disk = check_variable_if_none(request.POST['tic_disk'])
    tic_disk_ris = check_variable_if_none(request.POST['tic_disk_ris'])
    tcc_disk = check_variable_if_none(request.POST['tcc_disk'])
    tcc_disk_ris = check_variable_if_none(request.POST['tcc_disk_ris'])
    tob_disk = check_variable_if_none(request.POST['tob_disk'])
    tob_disk_ris = check_variable_if_none(request.POST['tob_disk_ris'])
    van_disk = check_variable_if_none(request.POST['van_disk'])
    van_disk_ris = check_variable_if_none(request.POST['van_disk_ris'])
    mfx_disk = check_variable_if_none(request.POST['mfx_disk'])
    mfx_disk_ris = check_variable_if_none(request.POST['mfx_disk_ris'])
    mem_disk = check_variable_if_none(request.POST['mem_disk'])
    mem_disk_ris = check_variable_if_none(request.POST['mem_disk_ris'])
    tzp_disk = check_variable_if_none(request.POST['tzp_disk'])
    tzp_disk_ris = check_variable_if_none(request.POST['tzp_disk_ris'])
    geh_disk = check_variable_if_none(request.POST['geh_disk'])
    geh_disk_ris = check_variable_if_none(request.POST['geh_disk_ris'])
    sth_disk = check_variable_if_none(request.POST['sth_disk'])
    sth_disk_ris = check_variable_if_none(request.POST['sth_disk_ris'])
    lnz_disk = check_variable_if_none(request.POST['lnz_disk'])
    lnz_disk_ris = check_variable_if_none(request.POST['lnz_disk_ris'])
    nov_disk = check_variable_if_none(request.POST['nov_disk'])
    nov_disk_ris = check_variable_if_none(request.POST['nov_disk_ris'])
    etp_disk = check_variable_if_none(request.POST['etp_disk'])
    etp_disk_ris = check_variable_if_none(request.POST['etp_disk_ris'])
    dor_disk = check_variable_if_none(request.POST['dor_disk'])
    dor_disk_ris = check_variable_if_none(request.POST['dor_disk_ris'])
    tgc_disk = check_variable_if_none(request.POST['tgc_disk'])
    tgc_disk_ris = check_variable_if_none(request.POST['tgc_disk_ris'])
    col_disk = check_variable_if_none(request.POST['col_disk'])
    col_disk_ris = check_variable_if_none(request.POST['col_disk_ris'])
    pol_disk = check_variable_if_none(request.POST['pol_disk'])
    pol_disk_ris = check_variable_if_none(request.POST['pol_disk_ris'])
    dox_disk = check_variable_if_none(request.POST['dox_disk'])
    dox_disk_ris = check_variable_if_none(request.POST['dox_disk_ris'])
    qda_disk = check_variable_if_none(request.POST['qda_disk'])
    qda_disk_ris = check_variable_if_none(request.POST['qda_disk_ris'])
    mno_disk = check_variable_if_none(request.POST['mno_disk'])
    mno_disk_ris = check_variable_if_none(request.POST['mno_disk_ris'])
    dap_disk = check_variable_if_none(request.POST['dap_disk'])
    dap_disk_ris = check_variable_if_none(request.POST['dap_disk_ris'])
    comments = check_variable_if_none(request.POST['comments'])
    
    
    save_disk = SiteDiskResult.objects.update_or_create(
        referred = referred,
        defaults={
    'amk_disk' : amk_disk,
    'amk_disk_ris' :  amk_disk_ris,
    'amc_disk' :  amc_disk,
    'amc_disk_ris' : amc_disk_ris,
    'amp_disk' : amp_disk, 
    'amp_disk_ris' : amp_disk_ris, 
    'sam_disk' : sam_disk, 
    'sam_disk_ris' : sam_disk_ris, 
    'atm_disk' : atm_disk,
    'atm_disk_ris' : atm_disk_ris,
    'azm_disk' : azm_disk, 
    'azm_disk_ris' : azm_disk_ris, 
    'cec_disk' : cec_disk, 
    'cec_disk_ris' : cec_disk_ris, 
    'man_disk' : man_disk, 
    'man_disk_ris' : man_disk_ris, 
    'czo_disk' : czo_disk, 
    'czo_disk_ris' : czo_disk_ris, 
    'fep_disk' : fep_disk, 
    'fep_disk_ris' : fep_disk_ris, 
    'cfm_disk' : cfm_disk, 
    'cfm_disk_ris' : cfm_disk_ris, 
    'cfp_disk' : cfp_disk, 
    'cfp_disk_ris' : cfp_disk_ris, 
    'ctx_disk' : ctx_disk, 
    'ctx_disk_ris' : ctx_disk_ris, 
    'fox_disk' : fox_disk, 
    'fox_disk_ris' : fox_disk_ris, 
    'caz_disk' : caz_disk, 
    'caz_disk_ris' : caz_disk_ris, 
    'cro_disk' : cro_disk, 
    'cro_disk_ris' : cro_disk_ris, 
    'cxa_disk' : cxa_disk, 
    'cxa_disk_ris' : cxa_disk_ris, 
    'cep_disk' : cep_disk, 
    'cep_disk_ris' : cep_disk_ris,
    'chl_disk' : chl_disk, 
    'chl_disk_ris' : chl_disk_ris, 
    'cip_disk' : cip_disk, 
    'cip_disk_ris' : cip_disk_ris, 
    'clr_disk' : clr_disk, 
    'clr_disk_ris' : clr_disk_ris, 
    'cli_disk' : cli_disk, 
    'cli_disk_ris' : cli_disk_ris, 
    'sxt_disk' : sxt_disk, 
    'sxt_disk_ris' : sxt_disk_ris, 
    'ery_disk' : ery_disk, 
    'ery_disk_ris' : ery_disk_ris, 
    'gen_disk' : gen_disk,  
    'gen_disk_ris' : gen_disk_ris, 
    'ipm_disk' : ipm_disk, 
    'ipm_disk_ris' : ipm_disk_ris, 
    'kan_disk' : kan_disk, 
    'kan_disk_ris' : kan_disk_ris, 
    'lev_disk' : lev_disk, 
    'lev_disk_ris' : lev_disk_ris, 
    'nal_disk' : nal_disk, 
    'nal_disk_ris' : nal_disk_ris, 
    'net_disk' : net_disk, 
    'net_disk_ris' : net_disk_ris, 
    'nit_disk' : nit_disk, 
    'nit_disk_ris' : nit_disk_ris, 
    'nor_disk' : nor_disk, 
    'nor_disk_ris' : nor_disk_ris, 
    'ofx_disk' : ofx_disk,
    'ofx_disk_ris' : ofx_disk_ris, 
    'oxa_disk' : oxa_disk, 
    'oxa_disk_ris' : oxa_disk_ris, 
    'pen_disk' : pen_disk, 
    'pen_disk_ris' : pen_disk_ris, 
    'pip_disk' : pip_disk, 
    'pip_disk_ris' : pip_disk_ris, 
    'rif_disk' : rif_disk, 
    'rif_disk_ris' : rif_disk_ris, 
    'spe_disk' : spe_disk, 
    'spe_disk_ris' : spe_disk_ris, 
    'str_disk' : str_disk, 
    'str_disk_ris' : str_disk_ris, 
    'tet_disk' : tet_disk, 
    'tet_disk_ris' : tet_disk_ris, 
    'tic_disk' : tic_disk, 
    'tic_disk_ris' : tic_disk_ris, 
    'tcc_disk' : tcc_disk, 
    'tcc_disk_ris' : tcc_disk_ris, 
    'tob_disk' : tob_disk, 
    'tob_disk_ris' : tob_disk_ris, 
    'van_disk' : van_disk, 
    'van_disk_ris' : van_disk_ris, 
    'mfx_disk' : mfx_disk, 
    'mfx_disk_ris' : mfx_disk_ris, 
    'mem_disk' : mem_disk, 
    'mem_disk_ris' : mem_disk_ris, 
    'tzp_disk' : tzp_disk, 
    'tzp_disk_ris' : tzp_disk_ris, 
    'geh_disk' : geh_disk, 
    'geh_disk_ris' : geh_disk_ris, 
    'sth_disk' : sth_disk, 
    'sth_disk_ris' : sth_disk_ris, 
    'lnz_disk' : lnz_disk, 
    'lnz_disk_ris' : lnz_disk_ris, 
    'nov_disk' : nov_disk, 
    'nov_disk_ris' : nov_disk_ris, 
    'etp_disk' : etp_disk, 
    'etp_disk_ris' : etp_disk_ris, 
    'dor_disk' : dor_disk, 
    'dor_disk_ris' : dor_disk_ris, 
    'tgc_disk' : tgc_disk, 
    'tgc_disk_ris' : tgc_disk_ris, 
    'col_disk' : col_disk, 
    'col_disk_ris' : col_disk_ris, 
    'pol_disk' : pol_disk, 
    'pol_disk_ris' : pol_disk_ris, 
    'dox_disk' : dox_disk, 
    'dox_disk_ris' : dox_disk_ris, 
    'qda_disk' : qda_disk, 
    'qda_disk_ris' : qda_disk_ris, 
    'mno_disk' : mno_disk, 
    'mno_disk_ris' : mno_disk_ris, 
    'dap_disk' : dap_disk, 
    'dap_disk_ris' : dap_disk_ris, 
    'comments' : comments, 
    'updated_by' : user
        }
    )
    
    
    amk_mic = check_variable_if_none(request.POST['amk_mic'])
    amk_mic_ris = check_variable_if_none(request.POST['amk_mic_ris'])
    amc_mic = check_variable_if_none(request.POST['amc_mic'])
    amc_mic_ris = check_variable_if_none(request.POST['amc_mic_ris'])
    amp_mic = check_variable_if_none(request.POST['amp_mic'])
    amp_mic_ris = check_variable_if_none(request.POST['amp_mic_ris'])
    sam_mic = check_variable_if_none(request.POST['sam_mic'])
    sam_mic_ris = check_variable_if_none(request.POST['sam_mic_ris'])
    atm_mic = check_variable_if_none(request.POST['atm_mic'])
    atm_mic_ris = check_variable_if_none(request.POST['atm_mic_ris'])
    azm_mic = check_variable_if_none(request.POST['azm_mic'])
    azm_mic_ris = check_variable_if_none(request.POST['azm_mic_ris'])
    cec_mic = check_variable_if_none(request.POST['cec_mic'])
    cec_mic_ris = check_variable_if_none(request.POST['cec_mic_ris'])
    man_mic = check_variable_if_none(request.POST['man_mic'])
    man_mic_ris = check_variable_if_none(request.POST['man_mic_ris'])
    czo_mic = check_variable_if_none(request.POST['czo_mic'])
    czo_mic_ris = check_variable_if_none(request.POST['czo_mic_ris'])
    fep_mic = check_variable_if_none(request.POST['fep_mic'])
    fep_mic_ris = check_variable_if_none(request.POST['fep_mic_ris'])
    cfm_mic = check_variable_if_none(request.POST['cfm_mic'])
    cfm_mic_ris = check_variable_if_none(request.POST['cfm_mic_ris'])
    cfp_mic = check_variable_if_none(request.POST['cfp_mic'])
    cfp_mic_ris = check_variable_if_none(request.POST['cfp_mic_ris'])
    ctx_mic = check_variable_if_none(request.POST['ctx_mic'])
    ctx_mic_ris = check_variable_if_none(request.POST['ctx_mic_ris'])
    fox_mic = check_variable_if_none(request.POST['fox_mic'])
    fox_mic_ris = check_variable_if_none(request.POST['fox_mic_ris'])
    caz_mic = check_variable_if_none(request.POST['caz_mic'])
    caz_mic_ris = check_variable_if_none(request.POST['caz_mic_ris'])
    cro_mic = check_variable_if_none(request.POST['cro_mic'])
    cro_mic_ris = check_variable_if_none(request.POST['cro_mic_ris'])
    cxa_mic = check_variable_if_none(request.POST['cxa_mic'])
    cxa_mic_ris = check_variable_if_none(request.POST['cxa_mic_ris'])
    cep_mic = check_variable_if_none(request.POST['cep_mic'])
    cep_mic_ris = check_variable_if_none(request.POST['cep_mic_ris'])
    chl_mic = check_variable_if_none(request.POST['chl_mic'])
    chl_mic_ris = check_variable_if_none(request.POST['chl_mic_ris'])
    cip_mic = check_variable_if_none(request.POST['cip_mic'])
    cip_mic_ris = check_variable_if_none(request.POST['cip_mic_ris'])
    clr_mic = check_variable_if_none(request.POST['clr_mic'])
    clr_mic_ris = check_variable_if_none(request.POST['clr_mic_ris'])
    cli_mic = check_variable_if_none(request.POST['cli_mic'])
    cli_mic_ris = check_variable_if_none(request.POST['cli_mic_ris'])
    sxt_mic = check_variable_if_none(request.POST['sxt_mic'])
    sxt_mic_ris = check_variable_if_none(request.POST['sxt_mic_ris'])
    ery_mic = check_variable_if_none(request.POST['ery_mic'])
    ery_mic_ris = check_variable_if_none(request.POST['ery_mic_ris'])
    gen_mic = check_variable_if_none(request.POST['gen_mic'])
    gen_mic_ris = check_variable_if_none(request.POST['gen_mic_ris'])
    ipm_mic = check_variable_if_none(request.POST['ipm_mic'])
    ipm_mic_ris = check_variable_if_none(request.POST['ipm_mic_ris'])
    kan_mic = check_variable_if_none(request.POST['kan_mic'])
    kan_mic_ris = check_variable_if_none(request.POST['kan_mic_ris'])
    lev_mic = check_variable_if_none(request.POST['lev_mic'])
    lev_mic_ris = check_variable_if_none(request.POST['lev_mic_ris'])
    nal_mic = check_variable_if_none(request.POST['nal_mic'])
    nal_mic_ris = check_variable_if_none(request.POST['nal_mic_ris'])
    net_mic = check_variable_if_none(request.POST['net_mic'])
    net_mic_ris = check_variable_if_none(request.POST['net_mic_ris'])
    nit_mic = check_variable_if_none(request.POST['nit_mic'])
    nit_mic_ris = check_variable_if_none(request.POST['nit_mic_ris'])
    nor_mic = check_variable_if_none(request.POST['nor_mic'])
    nor_mic_ris = check_variable_if_none(request.POST['nor_mic_ris'])
    ofx_mic = check_variable_if_none(request.POST['ofx_mic'])
    ofx_mic_ris = check_variable_if_none(request.POST['ofx_mic_ris'])
    oxa_mic = check_variable_if_none(request.POST['oxa_mic'])
    oxa_mic_ris = check_variable_if_none(request.POST['oxa_mic_ris'])
    pen_mic = check_variable_if_none(request.POST['pen_mic'])
    pen_mic_ris = check_variable_if_none(request.POST['pen_mic_ris'])
    pip_mic = check_variable_if_none(request.POST['pip_mic'])
    pip_mic_ris = check_variable_if_none(request.POST['pip_mic_ris'])
    rif_mic = check_variable_if_none(request.POST['rif_mic'])
    rif_mic_ris = check_variable_if_none(request.POST['rif_mic_ris'])
    spe_mic = check_variable_if_none(request.POST['spe_mic'])
    spe_mic_ris = check_variable_if_none(request.POST['spe_mic_ris'])
    str_mic = check_variable_if_none(request.POST['str_mic'])
    str_mic_ris = check_variable_if_none(request.POST['str_mic_ris'])
    tet_mic = check_variable_if_none(request.POST['tet_mic'])
    tet_mic_ris = check_variable_if_none(request.POST['tet_mic_ris'])
    tic_mic = check_variable_if_none(request.POST['tic_mic'])
    tic_mic_ris = check_variable_if_none(request.POST['tic_mic_ris'])
    tcc_mic = check_variable_if_none(request.POST['tcc_mic'])
    tcc_mic_ris = check_variable_if_none(request.POST['tcc_mic_ris'])
    tob_mic = check_variable_if_none(request.POST['tob_mic'])
    tob_mic_ris = check_variable_if_none(request.POST['tob_mic_ris'])
    van_mic = check_variable_if_none(request.POST['van_mic'])
    van_mic_ris = check_variable_if_none(request.POST['van_mic_ris'])
    mfx_mic = check_variable_if_none(request.POST['mfx_mic'])
    mfx_mic_ris = check_variable_if_none(request.POST['mfx_mic_ris'])
    mem_mic = check_variable_if_none(request.POST['mem_mic'])
    mem_mic_ris = check_variable_if_none(request.POST['mem_mic_ris'])
    tzp_mic = check_variable_if_none(request.POST['tzp_mic'])
    tzp_mic_ris = check_variable_if_none(request.POST['tzp_mic_ris'])
    geh_mic = check_variable_if_none(request.POST['geh_mic'])
    geh_mic_ris = check_variable_if_none(request.POST['geh_mic_ris'])
    sth_mic = check_variable_if_none(request.POST['sth_mic'])
    sth_mic_ris = check_variable_if_none(request.POST['sth_mic_ris'])
    lnz_mic = check_variable_if_none(request.POST['lnz_mic'])
    lnz_mic_ris = check_variable_if_none(request.POST['lnz_mic_ris'])
    nov_mic = check_variable_if_none(request.POST['nov_mic'])
    nov_mic_ris = check_variable_if_none(request.POST['nov_mic_ris'])
    etp_mic = check_variable_if_none(request.POST['etp_mic'])
    etp_mic_ris = check_variable_if_none(request.POST['etp_mic_ris'])
    dor_mic = check_variable_if_none(request.POST['dor_mic'])
    dor_mic_ris = check_variable_if_none(request.POST['dor_mic_ris'])
    tgc_mic = check_variable_if_none(request.POST['tgc_mic'])
    tgc_mic_ris = check_variable_if_none(request.POST['tgc_mic_ris'])
    col_mic = check_variable_if_none(request.POST['col_mic'])
    col_mic_ris = check_variable_if_none(request.POST['col_mic_ris'])
    pol_mic = check_variable_if_none(request.POST['pol_mic'])
    pol_mic_ris = check_variable_if_none(request.POST['pol_mic_ris'])
    dox_mic = check_variable_if_none(request.POST['dox_mic'])
    dox_mic_ris = check_variable_if_none(request.POST['dox_mic_ris'])
    qda_mic = check_variable_if_none(request.POST['qda_mic'])
    qda_mic_ris = check_variable_if_none(request.POST['qda_mic_ris'])
    mno_mic = check_variable_if_none(request.POST['mno_mic'])
    mno_mic_ris = check_variable_if_none(request.POST['mno_mic_ris'])
    dap_mic = check_variable_if_none(request.POST['dap_mic'])
    dap_mic_ris = check_variable_if_none(request.POST['dap_mic_ris'])
    
    
    save_mic = SiteMicResult.objects.update_or_create(
        referred = referred,
        defaults={
    'amk_mic' : amk_mic,
    'amk_mic_ris' :  amk_mic_ris,
    'amc_mic' :  amc_mic,
    'amc_mic_ris' : amc_mic_ris,
    'amp_mic' : amp_mic, 
    'amp_mic_ris' : amp_mic_ris, 
    'sam_mic' : sam_mic, 
    'sam_mic_ris' : sam_mic_ris, 
    'atm_mic' : atm_mic,
    'atm_mic_ris' : atm_mic_ris,
    'azm_mic' : azm_mic, 
    'azm_mic_ris' : azm_mic_ris, 
    'cec_mic' : cec_mic, 
    'cec_mic_ris' : cec_mic_ris, 
    'man_mic' : man_mic, 
    'man_mic_ris' : man_mic_ris, 
    'czo_mic' : czo_mic, 
    'czo_mic_ris' : czo_mic_ris, 
    'fep_mic' : fep_mic, 
    'fep_mic_ris' : fep_mic_ris, 
    'cfm_mic' : cfm_mic, 
    'cfm_mic_ris' : cfm_mic_ris, 
    'cfp_mic' : cfp_mic, 
    'cfp_mic_ris' : cfp_mic_ris, 
    'ctx_mic' : ctx_mic, 
    'ctx_mic_ris' : ctx_mic_ris, 
    'fox_mic' : fox_mic, 
    'fox_mic_ris' : fox_mic_ris, 
    'caz_mic' : caz_mic, 
    'caz_mic_ris' : caz_mic_ris, 
    'cro_mic' : cro_mic, 
    'cro_mic_ris' : cro_mic_ris, 
    'cxa_mic' : cxa_mic, 
    'cxa_mic_ris' : cxa_mic_ris, 
    'cep_mic' : cep_mic, 
    'cep_mic_ris' : cep_mic_ris,
    'chl_mic' : chl_mic, 
    'chl_mic_ris' : chl_mic_ris, 
    'cip_mic' : cip_mic, 
    'cip_mic_ris' : cip_mic_ris, 
    'clr_mic' : clr_mic, 
    'clr_mic_ris' : clr_mic_ris, 
    'cli_mic' : cli_mic, 
    'cli_mic_ris' : cli_mic_ris, 
    'sxt_mic' : sxt_mic, 
    'sxt_mic_ris' : sxt_mic_ris, 
    'ery_mic' : ery_mic, 
    'ery_mic_ris' : ery_mic_ris, 
    'gen_mic' : gen_mic,  
    'gen_mic_ris' : gen_mic_ris, 
    'ipm_mic' : ipm_mic, 
    'ipm_mic_ris' : ipm_mic_ris, 
    'kan_mic' : kan_mic, 
    'kan_mic_ris' : kan_mic_ris, 
    'lev_mic' : lev_mic, 
    'lev_mic_ris' : lev_mic_ris, 
    'nal_mic' : nal_mic, 
    'nal_mic_ris' : nal_mic_ris, 
    'net_mic' : net_mic, 
    'net_mic_ris' : net_mic_ris, 
    'nit_mic' : nit_mic, 
    'nit_mic_ris' : nit_mic_ris, 
    'nor_mic' : nor_mic, 
    'nor_mic_ris' : nor_mic_ris, 
    'ofx_mic' : ofx_mic,
    'ofx_mic_ris' : ofx_mic_ris, 
    'oxa_mic' : oxa_mic, 
    'oxa_mic_ris' : oxa_mic_ris, 
    'pen_mic' : pen_mic, 
    'pen_mic_ris' : pen_mic_ris, 
    'pip_mic' : pip_mic, 
    'pip_mic_ris' : pip_mic_ris, 
    'rif_mic' : rif_mic, 
    'rif_mic_ris' : rif_mic_ris, 
    'spe_mic' : spe_mic, 
    'spe_mic_ris' : spe_mic_ris, 
    'str_mic' : str_mic, 
    'str_mic_ris' : str_mic_ris, 
    'tet_mic' : tet_mic, 
    'tet_mic_ris' : tet_mic_ris, 
    'tic_mic' : tic_mic, 
    'tic_mic_ris' : tic_mic_ris, 
    'tcc_mic' : tcc_mic, 
    'tcc_mic_ris' : tcc_mic_ris, 
    'tob_mic' : tob_mic, 
    'tob_mic_ris' : tob_mic_ris, 
    'van_mic' : van_mic, 
    'van_mic_ris' : van_mic_ris, 
    'mfx_mic' : mfx_mic, 
    'mfx_mic_ris' : mfx_mic_ris, 
    'mem_mic' : mem_mic, 
    'mem_mic_ris' : mem_mic_ris, 
    'tzp_mic' : tzp_mic, 
    'tzp_mic_ris' : tzp_mic_ris, 
    'geh_mic' : geh_mic, 
    'geh_mic_ris' : geh_mic_ris, 
    'sth_mic' : sth_mic, 
    'sth_mic_ris' : sth_mic_ris, 
    'lnz_mic' : lnz_mic, 
    'lnz_mic_ris' : lnz_mic_ris, 
    'nov_mic' : nov_mic, 
    'nov_mic_ris' : nov_mic_ris, 
    'etp_mic' : etp_mic, 
    'etp_mic_ris' : etp_mic_ris, 
    'dor_mic' : dor_mic, 
    'dor_mic_ris' : dor_mic_ris, 
    'tgc_mic' : tgc_mic, 
    'tgc_mic_ris' : tgc_mic_ris, 
    'col_mic' : col_mic, 
    'col_mic_ris' : col_mic_ris, 
    'pol_mic' : pol_mic, 
    'pol_mic_ris' : pol_mic_ris, 
    'dox_mic' : dox_mic, 
    'dox_mic_ris' : dox_mic_ris, 
    'qda_mic' : qda_mic, 
    'qda_mic_ris' : qda_mic_ris, 
    'mno_mic' : mno_mic, 
    'mno_mic_ris' : mno_mic_ris, 
    'dap_mic' : dap_mic, 
    'dap_mic_ris' : dap_mic_ris, 
    'updated_by' : user
        }
    )
    
    amk_disk_ars = check_variable_if_none(request.POST['amk_disk_ars'])
    amk_disk_ris_ars = check_variable_if_none(request.POST['amk_disk_ris_ars'])
    amc_disk_ars = check_variable_if_none(request.POST['amc_disk_ars'])
    amc_disk_ris_ars = check_variable_if_none(request.POST['amc_disk_ris_ars'])
    amp_disk_ars = check_variable_if_none(request.POST['amp_disk_ars'])
    amp_disk_ris_ars = check_variable_if_none(request.POST['amp_disk_ris_ars'])
    sam_disk_ars = check_variable_if_none(request.POST['sam_disk_ars'])
    sam_disk_ris_ars = check_variable_if_none(request.POST['sam_disk_ris_ars'])
    atm_disk_ars = check_variable_if_none(request.POST['atm_disk_ars'])
    atm_disk_ris_ars = check_variable_if_none(request.POST['atm_disk_ris_ars'])
    azm_disk_ars = check_variable_if_none(request.POST['azm_disk_ars'])
    azm_disk_ris_ars = check_variable_if_none(request.POST['azm_disk_ris_ars'])
    cec_disk_ars = check_variable_if_none(request.POST['cec_disk_ars'])
    cec_disk_ris_ars = check_variable_if_none(request.POST['cec_disk_ris_ars'])
    man_disk_ars = check_variable_if_none(request.POST['man_disk_ars'])
    man_disk_ris_ars = check_variable_if_none(request.POST['man_disk_ris_ars'])
    czo_disk_ars = check_variable_if_none(request.POST['czo_disk_ars'])
    czo_disk_ris_ars = check_variable_if_none(request.POST['czo_disk_ris_ars'])
    fep_disk_ars = check_variable_if_none(request.POST['fep_disk_ars'])
    fep_disk_ris_ars = check_variable_if_none(request.POST['fep_disk_ris_ars'])
    cfm_disk_ars = check_variable_if_none(request.POST['cfm_disk_ars'])
    cfm_disk_ris_ars = check_variable_if_none(request.POST['cfm_disk_ris_ars'])
    cfp_disk_ars = check_variable_if_none(request.POST['cfp_disk_ars'])
    cfp_disk_ris_ars = check_variable_if_none(request.POST['cfp_disk_ris_ars'])
    ctx_disk_ars = check_variable_if_none(request.POST['ctx_disk_ars'])
    ctx_disk_ris_ars = check_variable_if_none(request.POST['ctx_disk_ris_ars'])
    fox_disk_ars = check_variable_if_none(request.POST['fox_disk_ars'])
    fox_disk_ris_ars = check_variable_if_none(request.POST['fox_disk_ris_ars'])
    caz_disk_ars = check_variable_if_none(request.POST['caz_disk_ars'])
    caz_disk_ris_ars = check_variable_if_none(request.POST['caz_disk_ris_ars'])
    cro_disk_ars = check_variable_if_none(request.POST['cro_disk_ars'])
    cro_disk_ris_ars = check_variable_if_none(request.POST['cro_disk_ris_ars'])
    cxa_disk_ars = check_variable_if_none(request.POST['cxa_disk_ars'])
    cxa_disk_ris_ars = check_variable_if_none(request.POST['cxa_disk_ris_ars'])
    cep_disk_ars = check_variable_if_none(request.POST['cep_disk_ars'])
    cep_disk_ris_ars = check_variable_if_none(request.POST['cep_disk_ris_ars'])
    chl_disk_ars = check_variable_if_none(request.POST['chl_disk_ars'])
    chl_disk_ris_ars = check_variable_if_none(request.POST['chl_disk_ris_ars'])
    cip_disk_ars = check_variable_if_none(request.POST['cip_disk_ars'])
    cip_disk_ris_ars = check_variable_if_none(request.POST['cip_disk_ris_ars'])
    clr_disk_ars = check_variable_if_none(request.POST['clr_disk_ars'])
    clr_disk_ris_ars = check_variable_if_none(request.POST['clr_disk_ris_ars'])
    cli_disk_ars = check_variable_if_none(request.POST['cli_disk_ars'])
    cli_disk_ris_ars = check_variable_if_none(request.POST['cli_disk_ris_ars'])
    sxt_disk_ars = check_variable_if_none(request.POST['sxt_disk_ars'])
    sxt_disk_ris_ars = check_variable_if_none(request.POST['sxt_disk_ris_ars'])
    ery_disk_ars = check_variable_if_none(request.POST['ery_disk_ars'])
    ery_disk_ris_ars = check_variable_if_none(request.POST['ery_disk_ris_ars'])
    gen_disk_ars = check_variable_if_none(request.POST['gen_disk_ars'])
    gen_disk_ris_ars = check_variable_if_none(request.POST['gen_disk_ris_ars'])
    ipm_disk_ars = check_variable_if_none(request.POST['ipm_disk_ars'])
    ipm_disk_ris_ars = check_variable_if_none(request.POST['ipm_disk_ris_ars'])
    kan_disk_ars = check_variable_if_none(request.POST['kan_disk_ars'])
    kan_disk_ris_ars = check_variable_if_none(request.POST['kan_disk_ris_ars'])
    lev_disk_ars = check_variable_if_none(request.POST['lev_disk_ars'])
    lev_disk_ris_ars = check_variable_if_none(request.POST['lev_disk_ris_ars'])
    nal_disk_ars = check_variable_if_none(request.POST['nal_disk_ars'])
    nal_disk_ris_ars = check_variable_if_none(request.POST['nal_disk_ris_ars'])
    net_disk_ars = check_variable_if_none(request.POST['net_disk_ars'])
    net_disk_ris_ars = check_variable_if_none(request.POST['net_disk_ris_ars'])
    nit_disk_ars = check_variable_if_none(request.POST['nit_disk_ars'])
    nit_disk_ris_ars = check_variable_if_none(request.POST['nit_disk_ris_ars'])
    nor_disk_ars = check_variable_if_none(request.POST['nor_disk_ars'])
    nor_disk_ris_ars = check_variable_if_none(request.POST['nor_disk_ris_ars'])
    ofx_disk_ars = check_variable_if_none(request.POST['ofx_disk_ars'])
    ofx_disk_ris_ars = check_variable_if_none(request.POST['ofx_disk_ris_ars'])
    oxa_disk_ars = check_variable_if_none(request.POST['oxa_disk_ars'])
    oxa_disk_ris_ars = check_variable_if_none(request.POST['oxa_disk_ris_ars'])
    pen_disk_ars = check_variable_if_none(request.POST['pen_disk_ars'])
    pen_disk_ris_ars = check_variable_if_none(request.POST['pen_disk_ris_ars'])
    pip_disk_ars = check_variable_if_none(request.POST['pip_disk_ars'])
    pip_disk_ris_ars = check_variable_if_none(request.POST['pip_disk_ris_ars'])
    rif_disk_ars = check_variable_if_none(request.POST['rif_disk_ars'])
    rif_disk_ris_ars = check_variable_if_none(request.POST['rif_disk_ris_ars'])
    spe_disk_ars = check_variable_if_none(request.POST['spe_disk_ars'])
    spe_disk_ris_ars = check_variable_if_none(request.POST['spe_disk_ris_ars'])
    str_disk_ars = check_variable_if_none(request.POST['str_disk_ars'])
    str_disk_ris_ars = check_variable_if_none(request.POST['str_disk_ris_ars'])
    tet_disk_ars = check_variable_if_none(request.POST['tet_disk_ars'])
    tet_disk_ris_ars = check_variable_if_none(request.POST['tet_disk_ris_ars'])
    tic_disk_ars = check_variable_if_none(request.POST['tic_disk_ars'])
    tic_disk_ris_ars = check_variable_if_none(request.POST['tic_disk_ris_ars'])
    tcc_disk_ars = check_variable_if_none(request.POST['tcc_disk_ars'])
    tcc_disk_ris_ars = check_variable_if_none(request.POST['tcc_disk_ris_ars'])
    tob_disk_ars = check_variable_if_none(request.POST['tob_disk_ars'])
    tob_disk_ris_ars = check_variable_if_none(request.POST['tob_disk_ris_ars'])
    van_disk_ars = check_variable_if_none(request.POST['van_disk_ars'])
    van_disk_ris_ars = check_variable_if_none(request.POST['van_disk_ris_ars'])
    mfx_disk_ars = check_variable_if_none(request.POST['mfx_disk_ars'])
    mfx_disk_ris_ars = check_variable_if_none(request.POST['mfx_disk_ris_ars'])
    mem_disk_ars = check_variable_if_none(request.POST['mem_disk_ars'])
    mem_disk_ris_ars = check_variable_if_none(request.POST['mem_disk_ris_ars'])
    tzp_disk_ars = check_variable_if_none(request.POST['tzp_disk_ars'])
    tzp_disk_ris_ars = check_variable_if_none(request.POST['tzp_disk_ris_ars'])
    geh_disk_ars = check_variable_if_none(request.POST['geh_disk_ars'])
    geh_disk_ris_ars = check_variable_if_none(request.POST['geh_disk_ris'])
    sth_disk_ars = check_variable_if_none(request.POST['sth_disk_ars'])
    sth_disk_ris_ars = check_variable_if_none(request.POST['sth_disk_ris_ars'])
    lnz_disk_ars = check_variable_if_none(request.POST['lnz_disk_ars'])
    lnz_disk_ris_ars = check_variable_if_none(request.POST['lnz_disk_ris_ars'])
    nov_disk_ars = check_variable_if_none(request.POST['nov_disk_ars'])
    nov_disk_ris_ars = check_variable_if_none(request.POST['nov_disk_ris_ars'])
    etp_disk_ars = check_variable_if_none(request.POST['etp_disk_ars'])
    etp_disk_ris_ars = check_variable_if_none(request.POST['etp_disk_ris_ars'])
    dor_disk_ars = check_variable_if_none(request.POST['dor_disk_ars'])
    dor_disk_ris_ars = check_variable_if_none(request.POST['dor_disk_ris_ars'])
    tgc_disk_ars = check_variable_if_none(request.POST['tgc_disk_ars'])
    tgc_disk_ris_ars = check_variable_if_none(request.POST['tgc_disk_ris_ars'])
    col_disk_ars = check_variable_if_none(request.POST['col_disk_ars'])
    col_disk_ris_ars = check_variable_if_none(request.POST['col_disk_ris_ars'])
    pol_disk_ars = check_variable_if_none(request.POST['pol_disk_ars'])
    pol_disk_ris_ars = check_variable_if_none(request.POST['pol_disk_ris_ars'])
    dox_disk_ars = check_variable_if_none(request.POST['dox_disk_ars'])
    dox_disk_ris_ars = check_variable_if_none(request.POST['dox_disk_ris_ars'])
    qda_disk_ars = check_variable_if_none(request.POST['qda_disk_ars'])
    qda_disk_ris_ars = check_variable_if_none(request.POST['qda_disk_ris_ars'])
    mno_disk_ars = check_variable_if_none(request.POST['mno_disk_ars'])
    mno_disk_ris_ars = check_variable_if_none(request.POST['mno_disk_ris_ars'])
    dap_disk_ars = check_variable_if_none(request.POST['dap_disk_ars'])
    dap_disk_ris_ars = check_variable_if_none(request.POST['dap_disk_ris_ars'])
    comments = check_variable_if_none(request.POST['comments'])
    
    
    ars_save_disk = ArsrlDiskResult.objects.update_or_create(
        referred = referred,
        defaults={
    'amk_disk' : amk_disk_ars,
    'amk_disk_ris' :  amk_disk_ris_ars,
    'amc_disk' :  amc_disk_ars,
    'amc_disk_ris' : amc_disk_ris_ars,
    'amp_disk' : amp_disk_ars, 
    'amp_disk_ris' : amp_disk_ris_ars, 
    'sam_disk' : sam_disk_ars, 
    'sam_disk_ris' : sam_disk_ris_ars, 
    'atm_disk' : atm_disk_ars,
    'atm_disk_ris' : atm_disk_ris_ars,
    'azm_disk' : azm_disk_ars, 
    'azm_disk_ris' : azm_disk_ris_ars, 
    'cec_disk' : cec_disk_ars, 
    'cec_disk_ris' : cec_disk_ris_ars, 
    'man_disk' : man_disk_ars, 
    'man_disk_ris' : man_disk_ris_ars, 
    'czo_disk' : czo_disk_ars, 
    'czo_disk_ris' : czo_disk_ris_ars, 
    'fep_disk' : fep_disk_ars, 
    'fep_disk_ris' : fep_disk_ris_ars, 
    'cfm_disk' : cfm_disk_ars, 
    'cfm_disk_ris' : cfm_disk_ris_ars, 
    'cfp_disk' : cfp_disk_ars, 
    'cfp_disk_ris' : cfp_disk_ris_ars, 
    'ctx_disk' : ctx_disk_ars, 
    'ctx_disk_ris' : ctx_disk_ris_ars, 
    'fox_disk' : fox_disk_ars, 
    'fox_disk_ris' : fox_disk_ris_ars, 
    'caz_disk' : caz_disk_ars, 
    'caz_disk_ris' : caz_disk_ris_ars, 
    'cro_disk' : cro_disk_ars, 
    'cro_disk_ris' : cro_disk_ris_ars, 
    'cxa_disk' : cxa_disk_ars, 
    'cxa_disk_ris' : cxa_disk_ris_ars, 
    'cep_disk' : cep_disk_ars, 
    'cep_disk_ris' : cep_disk_ris_ars,
    'chl_disk' : chl_disk_ars, 
    'chl_disk_ris' : chl_disk_ris_ars, 
    'cip_disk' : cip_disk_ars, 
    'cip_disk_ris' : cip_disk_ris_ars, 
    'clr_disk' : clr_disk_ars, 
    'clr_disk_ris' : clr_disk_ris_ars, 
    'cli_disk' : cli_disk_ars, 
    'cli_disk_ris' : cli_disk_ris_ars, 
    'sxt_disk' : sxt_disk_ars, 
    'sxt_disk_ris' : sxt_disk_ris_ars, 
    'ery_disk' : ery_disk_ars, 
    'ery_disk_ris' : ery_disk_ris_ars, 
    'gen_disk' : gen_disk_ars,  
    'gen_disk_ris' : gen_disk_ris_ars, 
    'ipm_disk' : ipm_disk_ars, 
    'ipm_disk_ris' : ipm_disk_ris_ars, 
    'kan_disk' : kan_disk_ars, 
    'kan_disk_ris' : kan_disk_ris_ars, 
    'lev_disk' : lev_disk_ars, 
    'lev_disk_ris' : lev_disk_ris_ars, 
    'nal_disk' : nal_disk_ars, 
    'nal_disk_ris' : nal_disk_ris_ars, 
    'net_disk' : net_disk_ars, 
    'net_disk_ris' : net_disk_ris_ars, 
    'nit_disk' : nit_disk_ars, 
    'nit_disk_ris' : nit_disk_ris_ars, 
    'nor_disk' : nor_disk_ars, 
    'nor_disk_ris' : nor_disk_ris_ars, 
    'ofx_disk' : ofx_disk_ars,
    'ofx_disk_ris' : ofx_disk_ris_ars, 
    'oxa_disk' : oxa_disk_ars, 
    'oxa_disk_ris' : oxa_disk_ris_ars, 
    'pen_disk' : pen_disk_ars, 
    'pen_disk_ris' : pen_disk_ris_ars, 
    'pip_disk' : pip_disk_ars, 
    'pip_disk_ris' : pip_disk_ris_ars, 
    'rif_disk' : rif_disk_ars, 
    'rif_disk_ris' : rif_disk_ris_ars, 
    'spe_disk' : spe_disk_ars, 
    'spe_disk_ris' : spe_disk_ris_ars, 
    'str_disk' : str_disk_ars, 
    'str_disk_ris' : str_disk_ris_ars, 
    'tet_disk' : tet_disk_ars, 
    'tet_disk_ris' : tet_disk_ris_ars, 
    'tic_disk' : tic_disk_ars, 
    'tic_disk_ris' : tic_disk_ris_ars, 
    'tcc_disk' : tcc_disk_ars, 
    'tcc_disk_ris' : tcc_disk_ris_ars, 
    'tob_disk' : tob_disk_ars, 
    'tob_disk_ris' : tob_disk_ris_ars, 
    'van_disk' : van_disk_ars, 
    'van_disk_ris' : van_disk_ris_ars, 
    'mfx_disk' : mfx_disk_ars, 
    'mfx_disk_ris' : mfx_disk_ris_ars, 
    'mem_disk' : mem_disk_ars, 
    'mem_disk_ris' : mem_disk_ris_ars, 
    'tzp_disk' : tzp_disk_ars, 
    'tzp_disk_ris' : tzp_disk_ris_ars, 
    'geh_disk' : geh_disk_ars, 
    'geh_disk_ris' : geh_disk_ris_ars, 
    'sth_disk' : sth_disk_ars, 
    'sth_disk_ris' : sth_disk_ris_ars, 
    'lnz_disk' : lnz_disk_ars, 
    'lnz_disk_ris' : lnz_disk_ris_ars, 
    'nov_disk' : nov_disk_ars, 
    'nov_disk_ris' : nov_disk_ris_ars, 
    'etp_disk' : etp_disk_ars, 
    'etp_disk_ris' : etp_disk_ris_ars, 
    'dor_disk' : dor_disk_ars, 
    'dor_disk_ris' : dor_disk_ris_ars, 
    'tgc_disk' : tgc_disk_ars, 
    'tgc_disk_ris' : tgc_disk_ris_ars, 
    'col_disk' : col_disk_ars, 
    'col_disk_ris' : col_disk_ris_ars, 
    'pol_disk' : pol_disk_ars, 
    'pol_disk_ris' : pol_disk_ris_ars, 
    'dox_disk' : dox_disk_ars, 
    'dox_disk_ris' : dox_disk_ris_ars, 
    'qda_disk' : qda_disk_ars, 
    'qda_disk_ris' : qda_disk_ris_ars, 
    'mno_disk' : mno_disk_ars, 
    'mno_disk_ris' : mno_disk_ris_ars, 
    'dap_disk' : dap_disk_ars, 
    'dap_disk_ris' : dap_disk_ris_ars, 
    'comments' : comments, 
    'updated_by' : user
        }
    )
    
    
    amk_mic_ars = check_variable_if_none(request.POST['amk_mic_ars'])
    amk_mic_ris_ars = check_variable_if_none(request.POST['amk_mic_ris_ars'])
    amc_mic_ars = check_variable_if_none(request.POST['amc_mic_ars'])
    amc_mic_ris_ars = check_variable_if_none(request.POST['amc_mic_ris_ars'])
    amp_mic_ars = check_variable_if_none(request.POST['amp_mic_ars'])
    amp_mic_ris_ars = check_variable_if_none(request.POST['amp_mic_ris_ars'])
    sam_mic_ars = check_variable_if_none(request.POST['sam_mic_ars'])
    sam_mic_ris_ars = check_variable_if_none(request.POST['sam_mic_ris_ars'])
    atm_mic_ars = check_variable_if_none(request.POST['atm_mic_ars'])
    atm_mic_ris_ars = check_variable_if_none(request.POST['atm_mic_ris_ars'])
    azm_mic_ars = check_variable_if_none(request.POST['azm_mic_ars'])
    azm_mic_ris_ars = check_variable_if_none(request.POST['azm_mic_ris_ars'])
    cec_mic_ars = check_variable_if_none(request.POST['cec_mic_ars'])
    cec_mic_ris_ars = check_variable_if_none(request.POST['cec_mic_ris_ars'])
    man_mic_ars = check_variable_if_none(request.POST['man_mic_ars'])
    man_mic_ris_ars = check_variable_if_none(request.POST['man_mic_ris_ars'])
    czo_mic_ars = check_variable_if_none(request.POST['czo_mic_ars'])
    czo_mic_ris_ars = check_variable_if_none(request.POST['czo_mic_ris_ars'])
    fep_mic_ars = check_variable_if_none(request.POST['fep_mic_ars'])
    fep_mic_ris_ars = check_variable_if_none(request.POST['fep_mic_ris_ars'])
    cfm_mic_ars = check_variable_if_none(request.POST['cfm_mic_ars'])
    cfm_mic_ris_ars = check_variable_if_none(request.POST['cfm_mic_ris_ars'])
    cfp_mic_ars = check_variable_if_none(request.POST['cfp_mic_ars'])
    cfp_mic_ris_ars = check_variable_if_none(request.POST['cfp_mic_ris_ars'])
    ctx_mic_ars = check_variable_if_none(request.POST['ctx_mic_ars'])
    ctx_mic_ris_ars = check_variable_if_none(request.POST['ctx_mic_ris_ars'])
    fox_mic_ars = check_variable_if_none(request.POST['fox_mic_ars'])
    fox_mic_ris_ars = check_variable_if_none(request.POST['fox_mic_ris_ars'])
    caz_mic_ars = check_variable_if_none(request.POST['caz_mic_ars'])
    caz_mic_ris_ars = check_variable_if_none(request.POST['caz_mic_ris_ars'])
    cro_mic_ars = check_variable_if_none(request.POST['cro_mic_ars'])
    cro_mic_ris_ars = check_variable_if_none(request.POST['cro_mic_ris_ars'])
    cxa_mic_ars = check_variable_if_none(request.POST['cxa_mic_ars'])
    cxa_mic_ris_ars = check_variable_if_none(request.POST['cxa_mic_ris_ars'])
    cep_mic_ars = check_variable_if_none(request.POST['cep_mic_ars'])
    cep_mic_ris_ars = check_variable_if_none(request.POST['cep_mic_ris_ars'])
    chl_mic_ars = check_variable_if_none(request.POST['chl_mic_ars'])
    chl_mic_ris_ars = check_variable_if_none(request.POST['chl_mic_ris_ars'])
    cip_mic_ars = check_variable_if_none(request.POST['cip_mic_ars'])
    cip_mic_ris_ars = check_variable_if_none(request.POST['cip_mic_ris_ars'])
    clr_mic_ars = check_variable_if_none(request.POST['clr_mic_ars'])
    clr_mic_ris_ars = check_variable_if_none(request.POST['clr_mic_ris_ars'])
    cli_mic_ars = check_variable_if_none(request.POST['cli_mic_ars'])
    cli_mic_ris_ars = check_variable_if_none(request.POST['cli_mic_ris_ars'])
    sxt_mic_ars = check_variable_if_none(request.POST['sxt_mic_ars'])
    sxt_mic_ris_ars = check_variable_if_none(request.POST['sxt_mic_ris_ars'])
    ery_mic_ars = check_variable_if_none(request.POST['ery_mic_ars'])
    ery_mic_ris_ars = check_variable_if_none(request.POST['ery_mic_ris_ars'])
    gen_mic_ars = check_variable_if_none(request.POST['gen_mic_ars'])
    gen_mic_ris_ars = check_variable_if_none(request.POST['gen_mic_ris_ars'])
    ipm_mic_ars = check_variable_if_none(request.POST['ipm_mic_ars'])
    ipm_mic_ris_ars = check_variable_if_none(request.POST['ipm_mic_ris_ars'])
    kan_mic_ars = check_variable_if_none(request.POST['kan_mic_ars'])
    kan_mic_ris_ars = check_variable_if_none(request.POST['kan_mic_ris_ars'])
    lev_mic_ars = check_variable_if_none(request.POST['lev_mic_ars'])
    lev_mic_ris_ars = check_variable_if_none(request.POST['lev_mic_ris_ars'])
    nal_mic_ars = check_variable_if_none(request.POST['nal_mic_ars'])
    nal_mic_ris_ars = check_variable_if_none(request.POST['nal_mic_ris_ars'])
    net_mic_ars = check_variable_if_none(request.POST['net_mic_ars'])
    net_mic_ris_ars = check_variable_if_none(request.POST['net_mic_ris_ars'])
    nit_mic_ars = check_variable_if_none(request.POST['nit_mic_ars'])
    nit_mic_ris_ars = check_variable_if_none(request.POST['nit_mic_ris_ars'])
    nor_mic_ars = check_variable_if_none(request.POST['nor_mic_ars'])
    nor_mic_ris_ars = check_variable_if_none(request.POST['nor_mic_ris_ars'])
    ofx_mic_ars = check_variable_if_none(request.POST['ofx_mic_ars'])
    ofx_mic_ris_ars = check_variable_if_none(request.POST['ofx_mic_ris_ars'])
    oxa_mic_ars = check_variable_if_none(request.POST['oxa_mic_ars'])
    oxa_mic_ris_ars = check_variable_if_none(request.POST['oxa_mic_ris_ars'])
    pen_mic_ars = check_variable_if_none(request.POST['pen_mic_ars'])
    pen_mic_ris_ars = check_variable_if_none(request.POST['pen_mic_ris_ars'])
    pip_mic_ars = check_variable_if_none(request.POST['pip_mic_ars'])
    pip_mic_ris_ars = check_variable_if_none(request.POST['pip_mic_ris_ars'])
    rif_mic_ars = check_variable_if_none(request.POST['rif_mic_ars'])
    rif_mic_ris_ars = check_variable_if_none(request.POST['rif_mic_ris_ars'])
    spe_mic_ars = check_variable_if_none(request.POST['spe_mic_ars'])
    spe_mic_ris_ars = check_variable_if_none(request.POST['spe_mic_ris_ars'])
    str_mic_ars = check_variable_if_none(request.POST['str_mic_ars'])
    str_mic_ris_ars = check_variable_if_none(request.POST['str_mic_ris_ars'])
    tet_mic_ars = check_variable_if_none(request.POST['tet_mic_ars'])
    tet_mic_ris_ars = check_variable_if_none(request.POST['tet_mic_ris_ars'])
    tic_mic_ars = check_variable_if_none(request.POST['tic_mic_ars'])
    tic_mic_ris_ars = check_variable_if_none(request.POST['tic_mic_ris_ars'])
    tcc_mic_ars = check_variable_if_none(request.POST['tcc_mic_ars'])
    tcc_mic_ris_ars = check_variable_if_none(request.POST['tcc_mic_ris_ars'])
    tob_mic_ars = check_variable_if_none(request.POST['tob_mic_ars'])
    tob_mic_ris_ars = check_variable_if_none(request.POST['tob_mic_ris_ars'])
    van_mic_ars = check_variable_if_none(request.POST['van_mic_ars'])
    van_mic_ris_ars = check_variable_if_none(request.POST['van_mic_ris_ars'])
    mfx_mic_ars = check_variable_if_none(request.POST['mfx_mic_ars'])
    mfx_mic_ris_ars = check_variable_if_none(request.POST['mfx_mic_ris_ars'])
    mem_mic_ars = check_variable_if_none(request.POST['mem_mic_ars'])
    mem_mic_ris_ars = check_variable_if_none(request.POST['mem_mic_ris_ars'])
    tzp_mic_ars = check_variable_if_none(request.POST['tzp_mic_ars'])
    tzp_mic_ris_ars = check_variable_if_none(request.POST['tzp_mic_ris_ars'])
    geh_mic_ars = check_variable_if_none(request.POST['geh_mic_ars'])
    geh_mic_ris_ars = check_variable_if_none(request.POST['geh_mic_ris_ars'])
    sth_mic_ars = check_variable_if_none(request.POST['sth_mic_ars'])
    sth_mic_ris_ars = check_variable_if_none(request.POST['sth_mic_ris_ars'])
    lnz_mic_ars = check_variable_if_none(request.POST['lnz_mic_ars'])
    lnz_mic_ris_ars = check_variable_if_none(request.POST['lnz_mic_ris_ars'])
    nov_mic_ars = check_variable_if_none(request.POST['nov_mic_ars'])
    nov_mic_ris_ars = check_variable_if_none(request.POST['nov_mic_ris_ars'])
    etp_mic_ars = check_variable_if_none(request.POST['etp_mic_ars'])
    etp_mic_ris_ars = check_variable_if_none(request.POST['etp_mic_ris_ars'])
    dor_mic_ars = check_variable_if_none(request.POST['dor_mic_ars'])
    dor_mic_ris_ars = check_variable_if_none(request.POST['dor_mic_ris_ars'])
    tgc_mic_ars = check_variable_if_none(request.POST['tgc_mic_ars'])
    tgc_mic_ris_ars = check_variable_if_none(request.POST['tgc_mic_ris_ars'])
    col_mic_ars = check_variable_if_none(request.POST['col_mic_ars'])
    col_mic_ris_ars = check_variable_if_none(request.POST['col_mic_ris_ars'])
    pol_mic_ars = check_variable_if_none(request.POST['pol_mic_ars'])
    pol_mic_ris_ars = check_variable_if_none(request.POST['pol_mic_ris_ars'])
    dox_mic_ars = check_variable_if_none(request.POST['dox_mic_ars'])
    dox_mic_ris_ars = check_variable_if_none(request.POST['dox_mic_ris_ars'])
    qda_mic_ars = check_variable_if_none(request.POST['qda_mic_ars'])
    qda_mic_ris_ars = check_variable_if_none(request.POST['qda_mic_ris_ars'])
    mno_mic_ars = check_variable_if_none(request.POST['mno_mic_ars'])
    mno_mic_ris_ars = check_variable_if_none(request.POST['mno_mic_ris_ars'])
    dap_mic_ars = check_variable_if_none(request.POST['dap_mic_ars'])
    dap_mic_ris_ars = check_variable_if_none(request.POST['dap_mic_ris_ars'])
    
    
    save_mic_ars = ArsrlMicResult.objects.update_or_create(
        referred = referred,
        defaults={
    'amk_mic' : amk_mic_ars,
    'amk_mic_ris' :  amk_mic_ris_ars,
    'amc_mic' :  amc_mic_ars,
    'amc_mic_ris' : amc_mic_ris_ars,
    'amp_mic' : amp_mic_ars, 
    'amp_mic_ris' : amp_mic_ris_ars, 
    'sam_mic' : sam_mic_ars, 
    'sam_mic_ris' : sam_mic_ris_ars, 
    'atm_mic' : atm_mic_ars,
    'atm_mic_ris' : atm_mic_ris_ars,
    'azm_mic' : azm_mic_ars, 
    'azm_mic_ris' : azm_mic_ris_ars, 
    'cec_mic' : cec_mic_ars, 
    'cec_mic_ris' : cec_mic_ris_ars, 
    'man_mic' : man_mic_ars, 
    'man_mic_ris' : man_mic_ris_ars, 
    'czo_mic' : czo_mic_ars, 
    'czo_mic_ris' : czo_mic_ris_ars, 
    'fep_mic' : fep_mic_ars, 
    'fep_mic_ris' : fep_mic_ris_ars, 
    'cfm_mic' : cfm_mic_ars, 
    'cfm_mic_ris' : cfm_mic_ris_ars, 
    'cfp_mic' : cfp_mic_ars, 
    'cfp_mic_ris' : cfp_mic_ris_ars, 
    'ctx_mic' : ctx_mic_ars, 
    'ctx_mic_ris' : ctx_mic_ris_ars, 
    'fox_mic' : fox_mic_ars, 
    'fox_mic_ris' : fox_mic_ris_ars, 
    'caz_mic' : caz_mic_ars, 
    'caz_mic_ris' : caz_mic_ris_ars, 
    'cro_mic' : cro_mic_ars, 
    'cro_mic_ris' : cro_mic_ris_ars, 
    'cxa_mic' : cxa_mic_ars, 
    'cxa_mic_ris' : cxa_mic_ris_ars, 
    'cep_mic' : cep_mic_ars, 
    'cep_mic_ris' : cep_mic_ris_ars,
    'chl_mic' : chl_mic_ars, 
    'chl_mic_ris' : chl_mic_ris_ars, 
    'cip_mic' : cip_mic_ars, 
    'cip_mic_ris' : cip_mic_ris_ars, 
    'clr_mic' : clr_mic_ars, 
    'clr_mic_ris' : clr_mic_ris_ars, 
    'cli_mic' : cli_mic_ars, 
    'cli_mic_ris' : cli_mic_ris_ars, 
    'sxt_mic' : sxt_mic_ars, 
    'sxt_mic_ris' : sxt_mic_ris_ars, 
    'ery_mic' : ery_mic_ars, 
    'ery_mic_ris' : ery_mic_ris_ars, 
    'gen_mic' : gen_mic_ars,  
    'gen_mic_ris' : gen_mic_ris_ars, 
    'ipm_mic' : ipm_mic_ars, 
    'ipm_mic_ris' : ipm_mic_ris_ars, 
    'kan_mic' : kan_mic_ars, 
    'kan_mic_ris' : kan_mic_ris_ars, 
    'lev_mic' : lev_mic_ars, 
    'lev_mic_ris' : lev_mic_ris_ars, 
    'nal_mic' : nal_mic_ars, 
    'nal_mic_ris' : nal_mic_ris_ars, 
    'net_mic' : net_mic_ars, 
    'net_mic_ris' : net_mic_ris_ars, 
    'nit_mic' : nit_mic_ars, 
    'nit_mic_ris' : nit_mic_ris_ars, 
    'nor_mic' : nor_mic_ars, 
    'nor_mic_ris' : nor_mic_ris_ars, 
    'ofx_mic' : ofx_mic_ars,
    'ofx_mic_ris' : ofx_mic_ris_ars, 
    'oxa_mic' : oxa_mic_ars, 
    'oxa_mic_ris' : oxa_mic_ris_ars, 
    'pen_mic' : pen_mic_ars, 
    'pen_mic_ris' : pen_mic_ris_ars, 
    'pip_mic' : pip_mic_ars, 
    'pip_mic_ris' : pip_mic_ris_ars, 
    'rif_mic' : rif_mic_ars, 
    'rif_mic_ris' : rif_mic_ris_ars, 
    'spe_mic' : spe_mic_ars, 
    'spe_mic_ris' : spe_mic_ris_ars, 
    'str_mic' : str_mic_ars, 
    'str_mic_ris' : str_mic_ris_ars, 
    'tet_mic' : tet_mic_ars, 
    'tet_mic_ris' : tet_mic_ris_ars, 
    'tic_mic' : tic_mic_ars, 
    'tic_mic_ris' : tic_mic_ris_ars, 
    'tcc_mic' : tcc_mic_ars, 
    'tcc_mic_ris' : tcc_mic_ris_ars, 
    'tob_mic' : tob_mic_ars, 
    'tob_mic_ris' : tob_mic_ris_ars, 
    'van_mic' : van_mic_ars, 
    'van_mic_ris' : van_mic_ris_ars, 
    'mfx_mic' : mfx_mic_ars, 
    'mfx_mic_ris' : mfx_mic_ris_ars, 
    'mem_mic' : mem_mic_ars, 
    'mem_mic_ris' : mem_mic_ris_ars, 
    'tzp_mic' : tzp_mic_ars, 
    'tzp_mic_ris' : tzp_mic_ris_ars, 
    'geh_mic' : geh_mic_ars, 
    'geh_mic_ris' : geh_mic_ris_ars, 
    'sth_mic' : sth_mic_ars, 
    'sth_mic_ris' : sth_mic_ris_ars, 
    'lnz_mic' : lnz_mic_ars, 
    'lnz_mic_ris' : lnz_mic_ris_ars, 
    'nov_mic' : nov_mic_ars, 
    'nov_mic_ris' : nov_mic_ris_ars, 
    'etp_mic' : etp_mic_ars, 
    'etp_mic_ris' : etp_mic_ris_ars, 
    'dor_mic' : dor_mic_ars, 
    'dor_mic_ris' : dor_mic_ris_ars, 
    'tgc_mic' : tgc_mic_ars, 
    'tgc_mic_ris' : tgc_mic_ris_ars, 
    'col_mic' : col_mic_ars, 
    'col_mic_ris' : col_mic_ris_ars, 
    'pol_mic' : pol_mic_ars, 
    'pol_mic_ris' : pol_mic_ris_ars, 
    'dox_mic' : dox_mic_ars, 
    'dox_mic_ris' : dox_mic_ris_ars, 
    'qda_mic' : qda_mic_ars, 
    'qda_mic_ris' : qda_mic_ris_ars, 
    'mno_mic' : mno_mic_ars, 
    'mno_mic_ris' : mno_mic_ris_ars, 
    'dap_mic' : dap_mic_ars, 
    'dap_mic_ris' : dap_mic_ris_ars, 
    'updated_by' : user
        }
    )
    
    ars_ampc = check_variable_if_none(request.POST['ars_ampc'])
    ars_esbl = check_variable_if_none(request.POST['ars_esbl'])
    ars_carb = check_variable_if_none(request.POST['ars_carb'])
    ars_ecim = check_variable_if_none(request.POST['ars_ecim'])
    ars_mcim = check_variable_if_none(request.POST['ars_mcim'])
    ars_ec_mcim = check_variable_if_none(request.POST['ars_ec_mcim'])
    ars_mbl = check_variable_if_none(request.POST['ars_mbl'])
    ars_bl = check_variable_if_none(request.POST['ars_bl'])
    ars_mr = check_variable_if_none(request.POST['ars_mr'])
    ars_meca = check_variable_if_none(request.POST['ars_meca'])
    ars_icr = check_variable_if_none(request.POST['ars_icr'])
    # ars_others = check_variable_if_none(request.POST['ars_others'])
    arsl_pre = check_variable_if_none(request.POST['arsl_pre'])
    ars_org_code = check_variable_if_none(request.POST['ars_org_code'])
    ars_org_name = check_variable_if_none(request.POST['ars_org_name'])
    arsrl_post = check_variable_if_none(request.POST['arsrl_post'])
    
    save_pheno_info_ars = ArsrlOrganismInformation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'ampc' : ars_ampc,
            'esbl' : ars_esbl,
            'carb' : ars_carb,
            'ecim' : ars_ecim,
            'mcim' : ars_mcim,
            'ec_mcim' : ars_ec_mcim,
            'mbl' : ars_mbl,
            'bl' : ars_bl,
            'mr' : ars_mr,
            'meca' : ars_meca,
            'icr' : ars_icr,
            # 'others' : ars_others,
            'arsl_pre' : arsl_pre,
            'org_code' : ars_org_code,
            'org_name' : ars_org_name,
            'arsrl_post' : arsrl_post,
            'updated_by' : user
        }
    )
    
    
    recommendation_code_ars = check_variable_if_none(request.POST['recommendation_code_ars'])
    recommendation_ars = check_variable_if_none(request.POST['recommendation_ars'])
    description_ars = check_variable_if_none(request.POST['description_ars'])
   
    
    save_recommendation_ars = ArsrlRecommendation.objects.update_or_create(
        referred = referred,
        defaults={
            'referred' : referred,
            'recommendation_code' : recommendation_code_ars,
            'recommendation' : recommendation_ars,
            'description' : description_ars,
            'updated_by' : user
        }
    )
    
    
    
    
    
    
    return save_patient_info




def check_variable_if_none(var):
    if var:
        return var
    elif var != '':
        return None
    else:
        return None